### ISSUE TITLE
recurring payments not being saved in database properly

### ISSUE THREAD

**Issue by wobrek** [MoneyFox/MoneyFox#1000]
Null pointer when modifying recurring payment after re-loading the program.

**Comment by wobrek** [comment]
recurring payments are always saved with Id = 0

**Comment by NPadrutt** [comment]
Ah, yeah. i see.

**Comment by NPadrutt** [comment]
Somehow the object isn't be updated.. mh.

**Comment by NPadrutt** [comment]
Somehow the object isn't be updated.. mh.

**Comment by sethbartlett** [comment]
Is this for android or Windows or both?

**Comment by NPadrutt** [comment]
Both
