### ISSUE TITLE
More options to personalize the live tile

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1020]
- List of the last Transactions
- Comparison of expenses to the last month.

**Comment by drew-wallace** [comment]
Maybe have a live tile per account showing the current balance.

**Comment by NPadrutt** [comment]
Sounds like a nice option! Do you wanna try to implement this! :)

**Comment by IsaacMorris1980** [comment]
@NPadrutt   I would like to try this one

**Comment by NPadrutt** [comment]
great :) I marked it as in progress for you.

**Comment by NPadrutt** [comment]
Actually I like all of these options / can see use in all of these. The one I would probably use is the comparing of the last months. But I think that's very personal. So I think it's up to you :)

When it comes to the tile updates, I think it would make sense to update them regularly in the background with a background job.

**Comment by IsaacMorris1980** [comment]
@NPadrutt  
You are correct i was going to use a background task for the updating.
1.  Showing last x transactions with x limited to 1-9?
2.  Comparing last months expenses to current expenses(text atlease ))? might be able to display charts
3.  Ability to create a live tile for each account to keep up to date on? - This will require updates to UI to allow user to select which accounts to pin and unpin(we may be able to programmably do it but i think we should leave to users discretion.
4.  Show user upcoming x transactions with x limited to 1-9 .

We have 2 different tiles 

The primary tile -  which all applications only has one of
 i was going with 1,2,4 and have it cycle through 
them(eg.  if it is displaying information from 1, then at a certian amount of time have it change to display information from 2 and so on) approx every 3 minutes or when ever we descide is a good time 

The secondary tiles(we can make as many as the user wants to) i was going with 3
but i am not sure what content would be good to show about each account besides the balance?  do you know anything else?

**Comment by NPadrutt** [comment]
mmh, you could add 2 to the individual account pages as well and there just considered the selected account?

**Comment by IsaacMorris1980** [comment]
how often should i have it update

**Comment by IsaacMorris1980** [comment]
@NPadrutt   I just need to add globalization and so far this is what i have and currently not configurable by users 

The primary tile - last 8 payments and next 8 payments they cycle every 3 minutes

Secondary tiles - balance and expenses from last month and currently on this month- updated every 3 minutes

I will be adding some issues to allow customization by users(so users can choose what to display on tiles)

What else am i overlooking?

**Comment by NPadrutt** [comment]
Fixed with PR #1458
