### ISSUE TITLE
Null exception in AccountListViewModel

### ISSUE THREAD

**Issue by MatthewJamesHill** [MoneyFox/MoneyFox#1036]
Hello! I've been looking for something to contribute to so I hope you don't mind my jumping in. It's a small issue but when running for the first time I get the exception below. Should there be a check for a null value before calling .Any() on AllAccounts?

System.ArgumentNullException was unhandled by user code
StackTrace:
       at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
       at MoneyFox.Shared.ViewModels.AccountListViewModel.get_IsAllAccountsEmpty()

**Comment by NPadrutt** [comment]
Hi Matthew!
We appreciate every contribution and are happy about everyone who want to contribute! =) 

That sounds reasonable. Although I wonder why it can be null anyway. I assumed that it will at least an empty observable collectiion.
Have you tried your fix? does it work?

PS: we have a slack channel. write me a mail if you wanna join there as well :)

**Comment by MatthewJamesHill** [comment]
#1037

Have created a new PR which no longer generates the exception. Thanks for the welcome, will send you an email!
MAtt

**Comment by NPadrutt** [comment]
Thanks for the PR. Guess we can close this issue then, right? =)

**Comment by MatthewJamesHill** [comment]
Yep, if you're happy 😊

Bit peculiar like you said though, I would've thought it would have returned an empty collection but not for some reason. Might have to peruse some documentation!
