### ISSUE TITLE
Input negative value into expense

### ISSUE THREAD

**Issue by Squawk09** [MoneyFox/MoneyFox#1052]
When adding an expense to an account.  If you input a negative amount i.e. "-100" it is treated as subtracting a negative number from the account or adding funds to the account.  I think it should handle this by ignoring the "-" symbol.

**Comment by NPadrutt** [comment]
oh, that's a good point =)

**Comment by NPadrutt** [comment]
This should be fixed with #972

**Comment by hchev001** [comment]
I'm going to work on this bug next

**Comment by NPadrutt** [comment]
This is fixed :)
