### ISSUE TITLE
Feature Request: Savings Projects

### ISSUE THREAD

**Issue by hchev001** [MoneyFox/MoneyFox#1115]
As a user I would like the ability to be able to transfer money from one of my income accounts to a "savings project". Although this could be facilitated by creating another account and just transferring. The attributes of  a "savings project" account would have: a starting amount, the ability to add or subtract a value from them, set a goal of how much money needs to be saved, set a date the goal value needs to be met by. It would also be nice if a progress bar of some sort could be used to display the progress of the "savings project"

**Comment by NPadrutt** [comment]
Should be included in #356. There fore closed here.
