### ISSUE TITLE
Issues with Edit Amount if it is converted with seperator sign

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1116]
if the amount is converted for example as: 3'505.50 it can't be parsed correctly to a double. There changes are not saved correctly.

**Comment by isLongoria** [comment]
I took a quick look at this, is there a design reason as to why when trying to parse amountstring to a double, CultureInfo.InvariantCulture is used? It looks like if we changed that to the CurrentCulture IFormatProvider this bug can be avoided.

**Comment by NPadrutt** [comment]
If I remember right, the reason for me to use CultureInfo.InvariantCulture was that the seperator sign was always the same. So I could just replace an potentialy wrong sign and parse it. Otherwise with the current culture sometimes a dot and sometimes a comma would be used.
Maybe in Addition: There where issues in some cultures (for example german or swiss german) who the wrong separator sign was shown on the mobile keyboard. 
But feel free to try it! Maybe I just did something wrong :) 

Let me know if you need help or so. We have a Slack channel. Just send me your mail if I shall invite you =)

**Comment by isLongoria** [comment]
Thanks! I'm pretty new to GitHub and contributing but I'm trying to get involved, I'd love to be added to the Slack channel my email is pima.89@gmail.com, just realized it was hidden from my profile.

**Comment by NPadrutt** [comment]
you have an invite :)
