### ISSUE TITLE
Mixed Translations appearing on Android Version

### ISSUE THREAD

**Issue by hchev001** [MoneyFox/MoneyFox#1118]
![screenshot_20161104-231737](https://cloud.githubusercontent.com/assets/21987154/20027258/768d4eec-a2e5-11e6-86dd-62b06435617d.png)
![screenshot_20161104-231743](https://cloud.githubusercontent.com/assets/21987154/20027260/79c5f168-a2e5-11e6-8209-fbbbcb4e5a67.png)

**Comment by NPadrutt** [comment]
oh yeah. I included the german version wrong.
