### ISSUE TITLE
App uses very high power in the background on Windows 10 Mobile Anniversary Update (Lumia 830)

### ISSUE THREAD

**Issue by jsxw01** [MoneyFox/MoneyFox#1133]
![wp_ss_20161117_0001 _li](https://cloud.githubusercontent.com/assets/23611817/20462111/7c90669e-af24-11e6-9327-4acf29eac441.jpg)

**Comment by NPadrutt** [comment]
Thanks for reporting! My best guess is, that the automated backup upload is running wild in background here. I look into this.

**Comment by NPadrutt** [comment]
@jsxw01  is this still an issue with the latest version?

**Comment by jsxw01** [comment]
@NPadrutt I block work in background for this app. I don't know)

**Comment by NPadrutt** [comment]
i think we can close that for now.

**Comment by jsxw01** [comment]
Yes! Now app used about 6% in the background (for 6 hours in night), although I don't use auto sync... But it is better then 74%))

**Comment by NPadrutt** [comment]
nice :) I assume there where a wrong registration of a background service so that it is always registered and often running even though it wouldn't do anything.
