### ISSUE TITLE
Enable the sharing of accounts with other users of the app

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1145]
this will requre a webservice who handles login and exchange of the information

**Comment by drew-wallace** [comment]
I actually do this already with my wife and I. I just signed into my OneDrive during the backup process on her phone.

**Comment by NPadrutt** [comment]
ah, good idea! :) 
The idea is to make it possible to share just a single account with someone else and not the whole app.  Also if you wanna share it with someone farer away it get's more difficult to enter the credentials :)

**Comment by NPadrutt** [comment]
Questionable if there is a use case for this. Therefore closed for now.
