### ISSUE TITLE
Archive old Backups

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1172]
There where rare occasions where a backup was not correctly saved, resulting in a empty backup who afterwards get distributed when having the backup sync enabled. to avoid this, we should archive the old backups.

**Comment by drew-wallace** [comment]
Due to #1182, this should be a high priority to reduce any possible data loss for other users.

**Comment by NPadrutt** [comment]
@drew-wallace I'm happy to report that I just implemented this one. I'm creating an update now . I hope I can publish this shortly.

**Comment by drew-wallace** [comment]
Thank you sir.

**Comment by NPadrutt** [comment]
@drew-wallace just wanted to let you know: the update still is in certification and I'm in talks with the store team... I keep you posted when it is published.

**Comment by drew-wallace** [comment]
Sounds good. Hopefully 🤞 they send it through.

**Comment by NPadrutt** [comment]
The update FINALLY passed.. Should be available soon :)
