### ISSUE TITLE
Add option in settings - security to choose between password and windows hello

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1177]

**Comment by NPadrutt** [comment]
@Squawk09 thought I create an issue for that so we can keep track of it.

**Comment by Squawk09** [comment]
@NPadrutt Oh I guess not. I was actually just working on that last night.  Can you mark it as work in progress.

**Comment by NPadrutt** [comment]
:D 
Alright, it is marked :)

**Comment by NPadrutt** [comment]
This should be done by @Squawk09. Thanks! :)

**Comment by Squawk09** [comment]
@NPadrutt  Yep, it is done
