### ISSUE TITLE
Loss of all data on Windows 10 Mobile

### ISSUE THREAD

**Issue by drew-wallace** [MoneyFox/MoneyFox#1182]
I can't remember exactly what I was doing, but the app crashed and when I brought it back up, all my accounts were gone.

If possible, could you put a protection in the backup logic to prevent overwriting the database with an empty backup?

**Comment by NPadrutt** [comment]
Hi @drew-wallace 
I'm sorry to hear that you lost all your data. 
I'm planning a change to archive backups rather than override them every time (Issue #1172). Hope to get this out soon.

**Comment by drew-wallace** [comment]
It's fine. I recently switched to Money Fox so I still have my other app until this gets fixed. I'll subscribed to that issue and wait for a fix.
