### ISSUE TITLE
Add default Categories on first use

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1184]

**Comment by Squawk09** [comment]
@NPadrutt can you mark this in progress. Thanks!

**Comment by NPadrutt** [comment]
done.
You could have a look at this together with #353. They would be about the same topic.

**Comment by Squawk09** [comment]
Oh, I just saw this.  Yea It would probably be good to just put this in an assistance class.

**Comment by NPadrutt** [comment]
thanks for your PR. I commented on it with some requests to change.

do you want to have a look at the setup wizard as well? :)

**Comment by Squawk09** [comment]
@NPadrutt Ok, I can implement the Assistant. Can you mark issue #353 in progress?

 What all do you think the assistant should do beside load default values in the categories?  

Should there be some sort of tutorial wizard that the user clicks through that gives a summary of all the different buttons and pages?

**Comment by NPadrutt** [comment]
Great :) is marked.

I'm not sure if it does make sense to explain all pages and buttons. They should hopefully be more or less self explanatory once you got started and know what you are looking for ^^ 
But I think it would be great if the wizard can explain the basic functions and helps you getting started. for example let you create your accounts (or the first account) and hints at where you can add payments. Also maybe you can hint at some of the more advanced features like creating a backup.

But don't let you distract too much from me. Think of what is most helpful for a first time user :)
