### ISSUE TITLE
transfers to exluded accounts have to be included to the end of month calculation

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1191]

**Comment by Matt-J-H** [comment]
I think I might like to pick this one up as my first issue. Could anyone give me a bit more information as to what I would need to do? What files I would need to work with?

**Comment by NPadrutt** [comment]
Hi Matt

When I'm not completely wrong, this should all be in the BalanceCculationManager. This class is under MoneyFox.Business/Managers.

**Comment by NPadrutt** [comment]
As of what you need to told: currently we select payments wo are not transfers to calculate the total balances of all accounts. We ignore transfers because they do not have an impact of the balance. But with the excluded accounts, there can be payments who do have an impact. 
So in general, we have to select the transfers as well and if it targets and excluded account we have to handle it as an expense and if it is charged on a excluded account like an income. Does that make sense?

**Comment by Matt-J-H** [comment]
So I'm doing this for GetTotalEndOfMonthBalance() but not for GetEndOfMonthBalanceForAccount()? Or am I checking for both?

For GetTotalEndOfMonthBalance() I can see the charged account Id but that's it. So I'm checking if the charged account Id is excluded and if it is I'm adding the payment amount to balance. 

But I'm not sure what this balance is so I can't tell if the transfer is coming in or going out.

For example, in GetEndOfMonthBalanceForAccount() I know what the origin account is as well as the charged account so I can tell if I should add or subtract the amount from balance. 

But with GetTotalEndOfMonthBalance() I can't tell if the transfer is going out or coming in so I don't know if I should add or subtract.

So are all of the transfers coming in/going out? If so which is it? 

Thanks for the help!

**Comment by NPadrutt** [comment]
I do not exactly understand what you mean with you can see the charged account ID. But I think the issue is for both, target and charged account.
The point here is, that when I have a transfer from account A to account B the total balance is the same, right?
But when I have a an transfer from a included account to a excluded this changes the total balance. the same when I have one from a exluded one to an included.

As far as I thought about it, there is no need for this change in the GetEndOfMonthBalanceForAccount() method. But correct me if I'm wrong.

Does that help you?

PS: we have a slack channel, send me a mail with your mail address if you wanna have an invite!

**Comment by Matt-J-H** [comment]
The problem is that I can't tell where the transfer is going, so I don't know if it is included -> excluded or excluded -> included.

In the tests, a payment has the information:
                       Data =
                                    {
                                        Id = 15,
                                        ChargedAccountId = 1,
                                        Amount = 100,
                                        Date = DateTime.Now,
                                        Type = paymentType
                                    }

What I need is the TargetAccountId so the data would look like:
                         Data =
                                    {
                                        Id = 15,
                                        ChargedAccountId = 1,
                                        TargetAccountId = 2,
                                        Amount = 100,
                                        Date = DateTime.Now,
                                        Type = paymentType
                                    }

A payment entity has a parameter TargetAccountId but it is optional:
                         public int? TargetAccountId { get; set; }

I can change the tests to include the TargetAccountId and use that in managing the transfers, but then you would have to always provide a TargetAccountId so this might interfere with other parts of the code, I'm not sure.

For now I will change the test cases to include a TargetAccountId and use that.

My email address is mjhietpas@gmail.com

Thanks

**Comment by Matt-J-H** [comment]
I will create a pull request with these changes so you guys can take a look.

**Comment by NPadrutt** [comment]
Aaaah, I see the point.
The reason why TargetAccountId is nullable and not required is that if you have a income or an expense you just use the charged account. The target account comes only into play when you have a transfer.

Actually there is a issue (#972) to refactor how transfer is working to the way that you would create two payments for a transfer: an expense and an income.

**Comment by Matt-J-H** [comment]
So will transfers always have a TargetAccountId included? 
If that is the case then I can use TargetAccountId and it should be okay because it will only try to use it when the payment type is a transfer.

**Comment by NPadrutt** [comment]
yes, exactly. Feel free to add a code comment to make that clear. :)

**Comment by Matt-J-H** [comment]
I submitted a pull request, let me know what you think

**Comment by NPadrutt** [comment]
I already left ypu a comment on the PR.

Ah and you should​have an invite to the slack channel.

**Comment by NPadrutt** [comment]
fix with #1236
