### ISSUE TITLE
Recurring Payments not added for days inbetween opening app

### ISSUE THREAD

**Issue by Squawk09** [MoneyFox/MoneyFox#1198]
Recurring payments only get subtracted on days you open the app. 

For example, if you create a daily recurring expense of $1 and you dont open the app for two days, it will not deducted money from your account for those two days.

**Comment by Squawk09** [comment]
I can also handle this issue.  I think there needs to be a variable that saves the date you log in so that you can compare the last login date to the present date and then handle any account changes.

**Comment by NPadrutt** [comment]
Yes that's indeed an issue.
Another solution would be to get the Backgroundtasks working. I set them up but never got them completly working unfortunately..

**Comment by NPadrutt** [comment]
Shall I mark it as in progress @Squawk09 ?

**Comment by Squawk09** [comment]
Yes go ahead, I will take a look at the Backgroundtasks

**Comment by NPadrutt** [comment]
I guess I managed to fix he background tasks. Or let's say I just reenabled them :P

**Comment by NPadrutt** [comment]
Wih them this should be fixed aswell. If yo want I can sign up for the beta flights so you can test this

**Comment by Squawk09** [comment]
Oh, so this issue is closed?

**Comment by NPadrutt** [comment]
if testing looks fine then we can close it yes. it was more or less included with making the sync of the backup in the background instead of on startup.

**Comment by NPadrutt** [comment]
sorry, I hope I didn't steal your issue :)

**Comment by Squawk09** [comment]
Oh, no worries. I dont mind at all. :)

**Comment by NPadrutt** [comment]
alright :)
