### ISSUE TITLE
Tooltips on Desktop

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1225]
There should be tooltips when you hover over a menu on the desktop.

**Comment by Tazkad** [comment]
hello.
Id like to do it.

**Comment by NPadrutt** [comment]
great! I mark it as in progress for you. :)

**Comment by NPadrutt** [comment]
Since there was no progress since over two years I remove the "in progress" label here .
@Tazkad  let me know if you still or again want to work on this :)

**Comment by ErickJeffries** [comment]
I'm new to Open Source contributions, I'd like to try this one out.

**Comment by ErickJeffries** [comment]
@NPadrutt, I added the tooltips using the same resource as the Content of the navigation item. 

2 things: 

1. Most of them used [Name].Title however one of them used [Name].Label. Should I resolve this in this PR or create an issue for that and a new PR for that change?
2. I would typically see more information in a tooltip that gives additional context. If that's desired, what's the desired pattern to make a resource change?

**Comment by NPadrutt** [comment]
hey @ErickJeffries 

happy to assign you.

To your questions:

1. if you can resolve that, that it is coherent, that would be great.
2. I'm not sure what you mean with the desired pattern of resource to change. Could you elaborate or give me an example?

**Comment by ErickJeffries** [comment]
@NPadrutt, I followed the translation documentation and gave it a try. Let me know on the PR review if I missed something. Interesting first try at this!

**Comment by NPadrutt** [comment]
@ErickJeffries  looks good. The translation part looks good too. As soon as the PR is merged the added strings will be translatable via crowdin.
My only hint would be to not commit changes to the appxmanifest, since otherwise I'll have to reassign the app with the store again. Given that you have to adjust it locally for development makes it a bit hacky. But I haven't found a better way to handle this so far.

**Comment by ErickJeffries** [comment]
Thanks, yeah found that out the hard way! I've used WPF in the past this was my first time looking at a UWP app so that part had me with a few more commits than expected.

**Comment by NPadrutt** [comment]
do you want to merge this PR as is or would you want to add more tooltips elsewhere in the application?

**Comment by ErickJeffries** [comment]
I haven't explored the application too far at this point. I'm thinking I'd like some more practice at this. Can we merge this PR and I'll take a look at the app and add an issue for the other areas where tooltips are needed? Just for repetition sake for me.

**Comment by NPadrutt** [comment]
sure!

**Comment by NPadrutt** [comment]
I close this for now. We'll see how this will be with MAUI.
