### ISSUE TITLE
Add support for shortcuts

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1246]
We should make use of shortcuts so that users can create payments directly from the homescreen.

**Comment by JohnMiz** [comment]
Is this still available?
What kind of shortcuts? Like buttons that moves the user to "create payment" screen?

**Comment by NPadrutt** [comment]
yes this is still available :) the idea here was a shortcut when you tap long on the icon in the launcher.
for example [here](https://www.google.ch/imgres?imgurl=https%3A%2F%2Fcloud.addictivetips.com%2Fwp-content%2Fuploads%2F2016%2F10%2Fandroid-app-shortcuts-2.png&imgrefurl=https%3A%2F%2Fwww.addictivetips.com%2Fandroid%2Fhow-to-use-app-shortcuts-in-android-7%2F&docid=HUL4JWSjEtCSFM&tbnid=kqUik3iNXGGV2M%3A&vet=1&w=320&h=569&safe=off&bih=1058&biw=1920&ved=0ahUKEwjb29mf_uLeAhWiiKYKHfoSAGQQMwg3KAAwAA&iact=c&ictx=1)

I thought of something like the three creation options ( create expense, income and transfer). But of course that's up for debate :)

**Comment by NPadrutt** [comment]
let me know if you want to have a look at this :)
