### ISSUE TITLE
Enable to open multiple instances of the app

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1247]
Currently you can just have one window open. It would be nice to be able have multiple of them open.

**Comment by IsaacMorris1980** [comment]
To get multiple instance support you would have to follow the following:

https://docs.microsoft.com/en-us/windows/uwp/launch-resume/multi-instance-uwp#opt-in-to-multi-instance-behavior

**Comment by NPadrutt** [comment]
nice, thanks for that. feel free to have a look at that and submit a PR if you want :)

**Comment by IsaacMorris1980** [comment]
Should we create a separate project for multiple instance support since we would need to fully redo the uwp app

**Comment by NPadrutt** [comment]
I would overwrite the current one.

**Comment by NPadrutt** [comment]
What we would have to test extensivly is this part:
To avoid race-conditions and contention issues, multi-instance apps need to take steps to partition/synchronize access to settings, app-local storage, and any other resource (such as user files, a data store, and so on) that can be shared among multiple instances. Standard synchronization mechanisms such as mutexes, semaphores, events, and and so on, are available.
