### ISSUE TITLE
New category view. Crash while clicking save.

### ISSUE THREAD

**Issue by ASobiechowski** [MoneyFox/MoneyFox#1281]
On Honor 7 Lite, on new category view, click save leads to a crash. 
On Visual Studio Emulator for Android is OK.

**Comment by NPadrutt** [comment]
Thanks for reporting. It might be that this issue occurs on all kinds of physical devices (or at least it does on the two I have here).
Do you want to try to fix this? :)

**Comment by sobeek89** [comment]
I have been studying xamarin for a month. And I think I'm still too weak for patches, but I'll see what I can do. :)

**Comment by NPadrutt** [comment]
I'm here if you need help :) also, drop me a mail with you mailaddress if you want to join our slack channel.
