### ISSUE TITLE
Cancel button on Microsoft Authenticate form

### ISSUE THREAD

**Issue by ASobiechowski** [MoneyFox/MoneyFox#1284]
Back button not working on Microsoft One Drive authenticate form. We have to kill application.  

_Sent from my HONOR NEM-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ASobiechowski** [comment]
Set this issue as bug on android, please.

**Comment by NPadrutt** [comment]
As far as I see we can't do a lot about this, since that behaviour is on the login page of OneDrive.

**Comment by IsaacMorris1980** [comment]
@NPadrutt  can we create a page that hosts a webview and host the login page within the webview so that we can close the page without relying on one drive login page?

**Comment by NPadrutt** [comment]
We can, but only when we rewrite the whole login process on each plattform by ourself. Currently we use a library by Microsoft for that.

**Comment by NPadrutt** [comment]
This is fixed with version 6.x and the new authentication process.
