### ISSUE TITLE
Jump List does no longer work

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1310]
Currently it just opens  the app, but doesn't navigate to the requested page.

**Comment by DanielBHughes** [comment]
I'd like to pick this up please?

**Comment by NPadrutt** [comment]
@DanielBHughes  I marked the issue as in Progress for you. Thanks! :)

**Comment by DanielBHughes** [comment]
Submitted PR for this -  https://github.com/MoneyFox/MoneyFox/pull/1345
