### ISSUE TITLE
Add Autocomplete for Comment fields

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1328]

**Comment by cloudstalker** [comment]
Where is the comment field? I can't seem to find it.

**Comment by NPadrutt** [comment]
Ah, that should be note fields. Question is if that is really useful. This was an idea I put down to keep it in mind (therefore marekd as idea :) ). Let me know what you opinion on this is.

**Comment by cloudstalker** [comment]
Coming to think of it, your other idea (the one regarding tags) might be great in conjunction with notes. Then in that case autocomplete is quite useful.

**Comment by NPadrutt** [comment]
Closed for now, since I'm not sure this is really helpful.
