### ISSUE TITLE
Add the average amount spent on a each category to the category summary

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1341]

**Comment by Omegatronics** [comment]
could you provide some description please?

**Comment by NPadrutt** [comment]
Sure. The idea.

**Comment by NPadrutt** [comment]
Sure. Currently in the category summary there is a list with the total amount spent for that category in the selected time frame.
The idea is to add rhe average spent as well so you can compare if it has increased ir decreased.

**Comment by NPadrutt** [comment]
closed in favor of #1349
