### ISSUE TITLE
Broken Description (Simplified Chinese)

### ISSUE THREAD

**Issue by cloudstalker** [MoneyFox/MoneyFox#1357]
The app supposedly support simplified Chinese but on top of that the app itself is still largely English, the description at Windows Store (Chinese) consists of mostly ????'s (see [screenshot](https://imgur.com/VP0W8lv)).

**Comment by NPadrutt** [comment]
Thanks for your report! There seems to be something very wrong with the store description. I assume there went something wrong with the encoding during the import of the release notes. I'll have a look at that in the evening.

Currently the translation of simplified chinese is bit lacking. You can see it here: https://crowdin.com/project/money-fox/zh-CN#

For any help to keep the translations up to date we're very greatful.

**Comment by cloudstalker** [comment]
@NPadrutt Sure I will help. Also, I notice that tradition Chinese is at 0%. I suggest you just copy simplified over. The people using traditional can understand simplified with no trouble.

**Comment by cloudstalker** [comment]
@NPadrutt Just stumbled across 

> "If you activate this setting after every change on the database a backup is made to OneDrive.
> Also if you launch the application there it will check if there are newer backups and restore it if so." 

It's ridiculously long if direct translated to Chinese. I made it something like "Turn on this switch to sync with OneDrive". What do you think?

**Comment by cloudstalker** [comment]
@NPadrutt I do not quite understand the meaning of 

> Set the amount of hours to sync the backup.

I thought the sync happens on change?

**Comment by NPadrutt** [comment]
The backup is uploaded when you change something on your current device. The other devices currently will check periodically if there is a new version and download it. With the setting who belongs to that text you can set interval for that.

**Comment by cloudstalker** [comment]
@NPadrutt So it is one way (download). You guys could consider modifying the description to make this clearer.

**Comment by NPadrutt** [comment]
mh how about this
"Set the interval to check for changed data." ?

**Comment by NPadrutt** [comment]
you mean if someone overrides changes with wrong translations?

**Comment by cloudstalker** [comment]
yeah say I change a account to 100 on device A then change the same account to -100 on device B

**Comment by cloudstalker** [comment]
Oh and maybe more wrong encodings here.
![image](https://user-images.githubusercontent.com/19384512/41299000-121983a4-6e95-11e8-9c1c-1c063586459d.png)

**Comment by NPadrutt** [comment]
aah, you mean with the backup. Generally the later wins. I think of using push notifications to improve the speed here. But so far I didn't had the time to try this out.

**Comment by NPadrutt** [comment]
uh, yeah. I'll check that as well. Probably have to look that up with the one who made the charting library.

**Comment by cloudstalker** [comment]
I am not an expert in financials but I think it's a bit weird.
![image](https://user-images.githubusercontent.com/19384512/41299221-960a0350-6e95-11e8-9da9-fda9d0537fcf.png)
you see it is 240 + 30 but the last graph I showed you indicates 263. Anything wrong or there is some hidden financial concept?

**Comment by NPadrutt** [comment]
The statistics have a default time range from the 1. of the month to the last. So if you have a payment on the 25. you won't see it in the account list today (since not cleared yet) but in the statistic.
You can see if a payment is cleared or not if there is a tick in the paymentlist. 
![image](https://user-images.githubusercontent.com/1764367/41299481-d4af520e-6e63-11e8-9822-57a7f31f477f.png)

If you don't have any uncleared payments in the time range there seems to be an issue here. In that case it would be greate if you could create a seperate issue for that and provice a db backup.

**Comment by cloudstalker** [comment]
Yes they are all cleared (with tick marks). How do I find the said database without linking to OneDrive or do I have to sync first?

**Comment by NPadrutt** [comment]
You can find the database on your local computer under this path: %userprofile%/AppData/Local/Packages/57598ApplySolutionsSoftwa.MoneyFox_de8w9y82qfkbg/LocalState

**Comment by cloudstalker** [comment]
OK my bad. When I created the first account I initialized it with 7 inside so false alarm XD. Value on create does not go to current month flow is it?

**Comment by NPadrutt** [comment]
ah, good to hear.
what do you mean with value on create?

**Comment by cloudstalker** [comment]
when I create an account I can put in some preset money inside

**Comment by NPadrutt** [comment]
Aaah, now I know what you mean. No isn't taken into account in the cash flow, since that money didn't necessarilly come in this month.

**Comment by cloudstalker** [comment]
Thanks for the clarification. So far I quite like your project. Are there other ways I can contribute after I finish the translation? Perhaps help you guys redesign UI, front end and stuff.

**Comment by NPadrutt** [comment]
Sure :)
Of course! Frontend / UI is always much appreciated. Just create an issue for things you see so we can discuss it. Then you can just create a pull request with you changes. :)

Also in the issue tracker is a category up-for-grabs, with issues I think could be a good entry point.

**Comment by NPadrutt** [comment]
ah, also we have a slack channel. if you want an invite, just drop me mail with your mailaddress.

**Comment by cloudstalker** [comment]
Thank you! Do I mail you at the mail address shown on your profile page or is there a message function for GitHub? Sorry, new in this.

**Comment by NPadrutt** [comment]
The one on my profile is fine :)

**Comment by NPadrutt** [comment]
btw, I submitted an update to the store with a fixed store description.. seems indeed there was something wrong with the encoding when I imported the listing information

**Comment by cloudstalker** [comment]
Yeah sure. The store page's description is fixed now. Just checked.

**Comment by cloudstalker** [comment]
Need help with this one

> You updated a recurring payment. Do you want to update the future Payments aswell?

Not sure what this means. I tried this function in the app there seemed to be no difference.
Also I experience crash (UWP) with recurring switch turned on. Will open an issue of this after I am done with translation.

**Comment by NPadrutt** [comment]
Let's say you have a recurring payment with an account of 100 and you change it to 150. If you click in this message on yes next payment will also be about 150. Otherwise it's still 100. Does that make it clearer?

That would be great. thanks :)

**Comment by cloudstalker** [comment]
@NPadrutt still not too sure no matter which yes/no I click after I change the value of the recurrence and hit save, it gives the same result to the recurrence in question where it always shows the new amount. Could that be because of the crash?

**Comment by NPadrutt** [comment]
On the current payment is no difference if you click yes or no. it only affects future payments. as in the example above: if you click yes the next payment who is created out of the recurrence has 150 as the amount as well. if you click no it will have 100. 

Please file an issue for the crash with the steps to reproduce, so that we can keep seperate issues seperate from each other ;)

"Finished clearing your payments." and "Recurring payments where created." are no longer used as far as I remember. I will check that and delete them if so.

An Income is a payment, But a payment can be either a income (salary) and expense (Anything your spend money on) or an transfer (when you move money from one account to another).

As far as I know there "Month" is nowhere used. There is a translation for monthly however.


T

**Comment by NPadrutt** [comment]
if you click no, the next time a payment is generated for your recurring payment, it still will have 100 as amount and not 150. So if you have a monthly payment for example this payment is generated on the 1. of the next month. But this dialog doesn't have anything to do with the current payment you are looking at or generate a new payment right now. 

As far as I know we don't need any translations for these.

**Comment by cloudstalker** [comment]
OK now I understand. Say I recur due next week, then next week's entry will be 100 instead of 150 is it?
![image](https://user-images.githubusercontent.com/19384512/41349026-1f740572-6f41-11e8-8435-affc312e075c.png)

**Comment by NPadrutt** [comment]
exactly.

Mh, These are taken directly from the system.  What region settings do you have set on your computer?

**Comment by cloudstalker** [comment]
Singapore which is where I am currently at. (under regions and languages)
I changed it to China but the problem persists. Can I clean the cache somewhere to see if that helps? (not sure how)

**Comment by NPadrutt** [comment]
I don't think that here is a cache to clear. We probably format something wrong here.

**Comment by cloudstalker** [comment]
> Feedback Money Fox
Is there any context for this?

**Comment by NPadrutt** [comment]
This is the subject for the Feedback Email.

**Comment by cloudstalker** [comment]
@NPadrutt I have finished and rectified some old translations that feels wrong. Hopefully all is going well :). Will see.

**Comment by cloudstalker** [comment]
@NPadrutt just updated a few translations which seemed weird translated by previous guys.

**Comment by NPadrutt** [comment]
Alright. I usually update the used translations before I release an update to the store.
