### ISSUE TITLE
Indicator for future recurring payments

### ISSUE THREAD

**Issue by cloudstalker** [MoneyFox/MoneyFox#1362]
If I modify/delete the current payment, there is no way of knowing/editing those. Can consider create a UX that shows recurring payments in the future (grayed out) that can also be edited.

**Comment by NPadrutt** [comment]
I think this would be fixed with #544

**Comment by cloudstalker** [comment]
> Have a look at it and if you want give it a go :)

Sure. I am actually thinking about improving the whole app, mainly the content side, trying to resolve most UI/UX relevant stuff (unresolved issues and others from me) all at once. Will present to you the visual prototypes using design softwares so that we get a better ground at discussing all the changes. I will go first with the UWP part.

In the mean time I will continue to test the app and let you know of the bugs I encounter as the design process alone can take quite a while.

**Comment by NPadrutt** [comment]
sounds great :)

**Comment by NPadrutt** [comment]
Closed since duplicate to #544
