### ISSUE TITLE
Some visual anomalies when shrinking the window in width

### ISSUE THREAD

**Issue by cloudstalker** [MoneyFox/MoneyFox#1364]
- Downsizing the window in width will result in a big "Welcome" at the top
- In same widths the hamburger button is barely seen. (Not a problem in dark theme)

![image](https://user-images.githubusercontent.com/19384512/41390638-15739438-6fc9-11e8-96da-10be788ca7bb.png)

These two happen at the transition point when the navigation column changes to a single hamburger button. (Win10M (RIP) version as well, as I understand that smaller width correspond to mobile platform UI?)

**Comment by NPadrutt** [comment]
Yes this will be targeted at a mobile or tablet platform.
Currently the hamburger button color button is set by a style to white. In that scenario we would have to adjust the color based on if the side panel is open or not. 
The welcome is strange though. Probably changes a state and starts showing the built in titles again.

**Comment by cloudstalker** [comment]
Built in? As in MS's template or some legacy stuff?

**Comment by NPadrutt** [comment]
see here: https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview

**Comment by cloudstalker** [comment]
> The header must be visible when NavigationView is in Minimal mode.

This means that we just have to replace "welcome" with "" I guess.

**Comment by NPadrutt** [comment]
I think this should be kinda fixed with #1389. Kinda in the sense of not ideal but ok for the moment.

**Comment by NPadrutt** [comment]
This should be fixes with with the new navigation view of winui.
