### ISSUE TITLE
Issues building MoneyFox.Windows

### ISSUE THREAD

**Issue by IsaacMorris1980** [MoneyFox/MoneyFox#1371]
In order to build MoneyFox.Windows had to remove EntranceNavigationTransistionInfo.isTargetElement From  Paymentlistview and user control paymentlistviewcontrol  kept getting failed to find the attached property

**Comment by NPadrutt** [comment]
Can you try to close the view windows and try it again? I had the issue some times that when a view is open it will find some issues there and stop building cause of them despite the fact that they cause no issue on runtime.

Btw, we have an slack channel. Such issues are sometimes easier discuess there. drop me a mail if you want an invite. you can find my mail in my profile.

**Comment by NPadrutt** [comment]
@IsaacMorris1980 could you solve this?

**Comment by IsaacMorris1980** [comment]
Issue is resolved via the steps above
