### ISSUE TITLE
Support Deeplinking?

### ISSUE THREAD

**Issue by IsaacMorris1980** [MoneyFox/MoneyFox#1378]
Should we support deeplinking(eg if the app allowed for setting reminders for payments and other things and when the reminder popped up(independent of app open) user would be able to select reminder and be taken to correct page(payment list page,add payment dialog etc...))

**Comment by cloudstalker** [comment]
I could think of two scenarios where this can be useful. First one is when synchronization happens (changes synced from another device), selecting this notification should take users to the syncing page. Second one is when recurrence happens, taking users to the related account payment page. In addition to this, if there is some kind of financial goal, upon recurrence happening one is also notified of whether or not the goal has been met and if not, tell the user of how much remaining.
Another possibility is letting users set a reminder for themselves to update their accounts (say every day 7pm). They are notified when nothing get added that day (apart from recurrences).

**Comment by NPadrutt** [comment]
Yes Deeplinking makes a lot of sense with notifications. So far we do not create any, but issues like #366 might change that.

**Comment by IsaacMorris1980** [comment]
If we integrate more of cortana into the app it will require deeplinking as well(eg. tell cortana to open payment list page or something like that

**Comment by NPadrutt** [comment]
I think for the moment, we don't have a real usecase for this. Therefore closed.
