### ISSUE TITLE
Navigation selected item not right after clicking "back"

### ISSUE THREAD

**Issue by cloudstalker** [MoneyFox/MoneyFox#1381]
To see this in one instance:
Open App -> Click settings -> Hit "back" button -> The selected item is not correct (i.e., it is still the previous page's item, in this case, settings)

**Comment by NPadrutt** [comment]
This can be fixed with a feature introduced in the current insider preview 17110.

https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#code-example
