### ISSUE TITLE
Support mouse back buttons

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1390]
On a lot of mice you have a back button. Currently if you click on this nothing happens. This should trigger a navigation back.

**Comment by IsaacMorris1980** [comment]
Click event needs to look for xbutton1(usually the back button)  and xbutton2(usually the forward button)

**Comment by NPadrutt** [comment]
Is there a way to do that globally or would that be done in every page separatly?

**Comment by IsaacMorris1980** [comment]
still checking

**Comment by IsaacMorris1980** [comment]
@NPadrutt  Yes it can be done globally not sure how to add to app you can check out this page  https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-history-and-backwards-navigation  it gives a small tutorial how to use back button i am assuming something similar can be used for forward buttons as well
