### ISSUE TITLE
No option to delete the whole recurrence

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1391]
If you delete a recurring payment in android over the context menu of the list view the dialog who should ask if you want to delete the whole recurrence is not appearing. Therefore the recurrence will be recreated the next month.

**Comment by eraser282** [comment]
Has this been fixed already? Couldn't reproduce this in the android simulator.

**Comment by NPadrutt** [comment]
Mmh.. maybe it was fixed the same was it was introduced: with a sideeffect ^^ have you checked if teh database was deleted properly from the database?
