### ISSUE TITLE
Auto Synching

### ISSUE THREAD

**Issue by cloudstalker** [MoneyFox/MoneyFox#1402]
Implement Auto Download (so that the synching behaves like OneDrive)

**Comment by cloudstalker** [comment]
I had some time earlier to think about our current synchronization and the auto syncing and came up with a user interaction (or custom xaml control, if you will) design shown below:

![image](https://user-images.githubusercontent.com/19384512/43139520-8a5ba3aa-8f84-11e8-9864-2bc6938a253b.png)

To me there are three states as shown in the illustration (logged out, logged in (synced), logged in (not synced)). If auto-sync is implemented though, the logged in (not-synced) should be rare.
The four yellow arrows indicate major transitions between states. The yellower ones are transitions requiring a double-click on the prior state and less ones require only single-click. In addition all four transitions will have animations. I have made some animations with Flash, you can check them out below.

http://www.fastswf.com/2pCm474
http://www.fastswf.com/KbP6jpk

As always, it is ideal if the syncing process is hooked with the fullness of the cloud icon. Reversing the first animation will essentially leads to the other two transitions (logging off's) so I did not make them.

If I missed anything feel free to point that out.

Side note: Flash files can be outputted as html/javascript. Wonder if that can be somehow used.

**Comment by NPadrutt** [comment]
I really like the design and the icons!

**Comment by cloudstalker** [comment]
I am glad you like it!
I really hope there is someone can help me with some frontend stuff so that I can focus on designing and making custom controls, stuff like this. That's why I thought it would be supreme if Adobe CC could auto generate whatever things I make into code lol then I don't need help.

**Comment by NPadrutt** [comment]
Due to lack of activity closed. If problems with the sync occure please open a new issue.
