### ISSUE TITLE
Sqlite Error 

### ISSUE THREAD

**Issue by IsaacMorris1980** [MoneyFox/MoneyFox#1420]
When running accountservice.Getallaccounts()  getting no table named accounts

I have 2 accounts setup labeled checking and savings

**Comment by IsaacMorris1980** [comment]
i updated my repo with latest commits and is still am recieving the error

**Comment by IsaacMorris1980** [comment]
I am currently running this error down

**Comment by NPadrutt** [comment]
I think I have a similar issue on android in the latest beta update when the app is launched from suspended state. Did you get any further insights here?

**Comment by IsaacMorris1980** [comment]
From what I have seen so far the the dbcontextfactory and ambientdbcontextlocator are both null but I could be wrong

**Comment by IsaacMorris1980** [comment]
retried running latest build and #1427  fixed the issue

**Comment by IsaacMorris1980** [comment]
closing issue
