### ISSUE TITLE
Lock Screen Notifications?

### ISSUE THREAD

**Issue by IsaacMorris1980** [MoneyFox/MoneyFox#1425]
Should we implement lock screen notifications to allow content from the app if needed to be displayed to the user without unlocking device?

**Comment by NPadrutt** [comment]
I assume you mean the lock screen on Windows right?
What kind of information have you thought of?

**Comment by IsaacMorris1980** [comment]
Programably it is no different the live tiles just different handling

**Comment by IsaacMorris1980** [comment]
I was thinking similar to #1020 the live tiles,  although lockscreen notifications are limited in amount of content they can display(eg. lines of text they can display)

**Comment by NPadrutt** [comment]
I close this issue since so far we don't seem to have a concrete vision for that. If I'm mistaken, please reopen.
