### ISSUE TITLE
Use Logging Framework

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1428]
Since AppCenter has no support for Tracking Exceptions on UWP, we should introduce a logging framework who allows to log to a log file.

**Comment by IsaacMorris1980** [comment]
do we want to create our own or use frameworks like nlog?

**Comment by NPadrutt** [comment]
Definitely use a existing one like nlog. Create a own doesn't really make sense I think.

**Comment by NPadrutt** [comment]
This can be used as described here: https://www.mvvmcross.com/documentation/fundamentals/logging
