### ISSUE TITLE
Root Checks for Android Devices?

### ISSUE THREAD

**Issue by IsaacMorris1980** [MoneyFox/MoneyFox#1434]
Should we check for rooted devices and disallow or warn user that logging into accounts may not be safe on rooted devices?  

In a rooted device normal system security can be bypassed

**Comment by NPadrutt** [comment]
mmh, I'm not sure that this is necessary. I think if you have a device you use and it is rooted you did that yourself and by purpose.

**Comment by IsaacMorris1980** [comment]
If we ever add functionality to connect to banks(eg. pull up to date information from accounts) this should be revisited. 

Closing per comment

**Comment by NPadrutt** [comment]
absolutly.
