### ISSUE TITLE
Implement In app prompts?

### ISSUE THREAD

**Issue by IsaacMorris1980** [MoneyFox/MoneyFox#1438]
Should we implement in app prompts similar to the snackbar notification in android so we can update our user on things that have been running in the background are complete(eg. live tile was created, backup or restore finally complete, etc......)

**Comment by NPadrutt** [comment]
there would be the option of the usual notifications. But i'm not sure about these since they always land in the notificaton center and fill that up.. Or we would have to implement something new. Might be worth a thought.

**Comment by IsaacMorris1980** [comment]
This would be a new implementation, Usual notifications do fill up the notification center, in app prompts are messages only displayed in the app not using notification(action) center.In app prompts slid up into the page with the message then slides out of the page when message time has been completed

**Comment by IsaacMorris1980** [comment]
i would like to try this one

**Comment by NPadrutt** [comment]
Alright it's marked as in progress for you :)

**Comment by IsaacMorris1980** [comment]
Which pages should we have the in-app prompt display on?

On android and ios do they get their forms from

**Comment by IsaacMorris1980** [comment]
@NPadrutt  not sure how to do android and ios

**Comment by NPadrutt** [comment]
Mmh,maybe toasts are a option for android?

**Comment by NPadrutt** [comment]
Since there was no progress on this issue for quite some time and also a couple of libraries we could use for that purpose I close this issue.
