### ISSUE TITLE
recurring payments not being correctly displayed in payment object

### ISSUE THREAD

**Issue by IsaacMorris1980** [MoneyFox/MoneyFox#1451]
@NPadrutt 
 When i save a recurring payment then call paymentService.GetPaymentsByAccountId(accountid)  and ieterate on all payments i get a null exception error when attempting to call anything  payment.data.recurringpayment.{any part of recurring payment}.   The payment object is labeled as a recurring payment but the recurring payment part of the payment is always null.  The recurring payment is saved correctly in the database as if you run the following function and pass in the recurring payment id from the payment object it correctly pulls the correct reccurring payment:

            public RecurringPayment GetReccuringPaymentById(int? recurringPaymentId)
		{
			using (dbContextScopeFactory.CreateReadOnly())
			{
				using (var dbContext = ambientDbContextLocator.Get<ApplicationContext>())
				{
					return new RecurringPayment(dbContext.RecurringPayments.FirstOrDefault(x => x.Id == recurringPaymentId));

				}
			}
		}

I have temporaraly added this funtion to the recurring payment service to test #1020

**Comment by NPadrutt** [comment]
aah, yeah I see the confusion. The method `paymentService.GetPaymentsByAccountId(accountid) ` does not link the recurring payments. Therefore it is null. If you need it you can add an include in the PaymentService (around line 131). This should look similar to the Include of the Category.

**Comment by IsaacMorris1980** [comment]
@NPadrutt Now that i know what it does i only need start date, end date, amount and recurrance only when attempting to get the next 8 payments  for the live tiles.  I will add the include on the that function in payment service.
