### ISSUE TITLE
Recurring payment start date incorrect

### ISSUE THREAD

**Issue by IsaacMorris1980** [MoneyFox/MoneyFox#1457]
When iterating over a list of payment entities and checking the attached recurring payment entities start date the start date displays as the last cleared recurring payment not the date when the recurring payment was first created

**Comment by NPadrutt** [comment]
@IsaacMorris1980  can you check if this is still the case? I didn't experience that with the new code.

**Comment by IsaacMorris1980** [comment]
@NPadrutt   It was working correctly when initial pr for live tiles was created forgot to add this number into pr
