### ISSUE TITLE
Adaptive numbers on live tiles

### ISSUE THREAD

**Issue by IsaacMorris1980** [MoneyFox/MoneyFox#1460]
On small and medium live tiles truncate numbers  so they will fit on tile.  Eg.  1,500.00 would be come 1.5K currently it would display 1,50.......  if you had 1511.31 no truncation is available

**Comment by IsaacMorris1980** [comment]
i would like to try this

**Comment by NPadrutt** [comment]
great. Marked as in progress :)

**Comment by IsaacMorris1980** [comment]
This will be added to pr for #1466
