### ISSUE TITLE
Add Issue and PR templates

### ISSUE THREAD

**Issue by pablojimpas** [MoneyFox/MoneyFox#1470]
Hi! I think is a great idea to complete this checklist adding Issues and PR templates in order to make it easier for newbies to contribute but also for users that want to report bugs.
In summary, is a good practice in open source projects.

![imagen](https://user-images.githubusercontent.com/17835916/50616430-cb72a300-0ee8-11e9-8736-6e83a607ae76.png)

PS: GitHub makes this really easy for the project maintainer providing a default template for "Bugs" and "Features requets" accesible via the "Community" section under the "Insights" tab. For more specific templates related to UWP you can check out Windows Community Toolkit [Issue ](https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/master/.github/ISSUE_TEMPLATE.md) and [PR](https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/master/.github/PULL_REQUEST_TEMPLATE.md) templates.

**Comment by NPadrutt** [comment]
Good point and thanks for the resources :)

**Comment by NPadrutt** [comment]
Done. If you have suggestions for alterations, let me know.

**Comment by pablojimpas** [comment]
Great! Wrapping all this GitHub related documents under the .github folder will be great also. You migh have to change some links as well.
