### ISSUE TITLE
Total expenses and income for category overview

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1482]
**Is your feature request related to a problem? Please describe.**

In the category summary you can see all the expenses and incomes. But no summaries of them.

**Describe the solution you'd like**
In the category summary on the top of the list should be a total for the incomes and expenses similar to the balance overview in the account or payment list.

**Describe alternatives you've considered**

**Additional context**

**Comment by snehansh** [comment]
I am interested to take this issue.

**Comment by NPadrutt** [comment]
Is marked as in progress. :)

**Comment by Sreini** [comment]
@NPadrutt can this issue be closed?

**Comment by NPadrutt** [comment]
yes, thank you!
