### ISSUE TITLE
Monthly Balance is not calculated correctly

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1493]
**Describe the bug**
I have a End Of Month Sum of -15 and when I add a income of 700 it jumps to 1385.

**Expected behavior**
The sum should be calculated correctly.

**Comment by RobBentleyDev** [comment]
On first impressions, I'd say the Income value is being added twice... 700 + 700 = 1400 - 15 = 1385.

**Comment by NPadrutt** [comment]
True. Interesstingly on my debug build it's calculated correctly. Maybe this is already fixed with something not rolled out on windows.

**Comment by NPadrutt** [comment]
With the current version this seems fixed too.
