### ISSUE TITLE
Page transition animations are not consistent for all main pages

### ISSUE THREAD

**Issue by RobBentleyDev** [MoneyFox/MoneyFox#1497]
**Describe the bug**
When navigating between pages the page transition for the "Select Statistic" and "Settings" pages is inconsistent with the other pages.

**To Reproduce**
1. Go to the "Accounts" page
2. Go to the "Select Statistic" page
3. Observe that the title for "Select Statistic" page TITLE appears instantly rather than being animated into place along with the rest of the content as it does on other pages.

**Expected behavior**
Both the "Select Statistic" and "Settings" pages should transition their content into place via a page transition animation, consistent with other pages. 

**Screenshots**
The page animations are subtle and difficult to convey via screenshots. The effect can be seen in the released Store App and more-so (on my machine anyway) when running the app in Debug mode. See the screenshots below for the area of the screen to focus on when going from one page to another (as highlighted in yellow.

![image](https://user-images.githubusercontent.com/12400623/52439884-8dceee80-2b14-11e9-9961-83e0889c4a3a.png)

![image](https://user-images.githubusercontent.com/12400623/52439898-94f5fc80-2b14-11e9-9001-642a2c4b0b08.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (UWP)
 - Version 17763

**Smartphone (please complete the following information):**
not applicable

**Additional context**

The fix is relatively simple, and detailed below... 

StatisticSelectorView.xaml
EntranceNavigationTransitionInfo.IsTargetElement="True"
should be on outermost Grid element rather than the child ScrollViewer

SettingsView.xaml
This view had no page transition at all. EntranceNavigationTransitionInfo.IsTargetElement="True"
should be added on outermost Grid element.

I would like to do the changes and submit a Pull Request, however are there any other pages where the page transition animation should affect the entire content of the page rather than just a portion of it? I don't know whether not animating it is by design or not. Please can you clarify?

**Comment by NPadrutt** [comment]
Hi @RobBentleyDev 

Thanks for your issue. I think the entrance navigation, as you noted, should be on all pages the same. Therefore I think if it is somewhere missing it isn't by design. If you can check and add where it is missing that would be great!

**Comment by RobBentleyDev** [comment]
Thanks @NPadrutt, I'll go through all of the pages over the weekend and add the page transition as necessary and create a PR.

**Comment by RobBentleyDev** [comment]
This issues has now been resolved.
