### ISSUE TITLE
Entry fields for recurring payments clickable although not visible

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1500]
**Describe the bug**
When you create a payment as a default it is not recurring. Therefore the entry fields for the recurring options are not visible. But when you click around in the blank space you can still interact with them.

**To Reproduce**
1. Go to Add Payment page
2. Click around in the blank space beneath the "Is recurring togle"
3. See that the enum fields or date picker opens

**Expected behavior**
The controls can not be clicked. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1764367/52521191-bc171000-2c73-11e9-8705-aa0bb04fb8d9.png)

**Desktop (please complete the following information):**
 - OS: Windows 1809
 - Version 5.0.1265

**Smartphone (please complete the following information):**
Does not apply

**Additional context**
Probably the fade effect does just set the controls to transparent and does not collapse them.

**Comment by gabrielatricak** [comment]
Hi i would like to work on this. Can I be assigned to this?

**Comment by NPadrutt** [comment]
@gabrielatricak sure, I added you. :)

**Comment by NPadrutt** [comment]
This was fixed with a refactoring of the add payment page.
