### ISSUE TITLE
Accounts can not be deleted

### ISSUE THREAD

**Issue by RobBentleyDev** [MoneyFox/MoneyFox#1526]
**Describe the bug**
Delete Account menu option does not actually delete the account.

**To Reproduce**
1. Go to Accounts List page.
2. Open the Account Context menu (swipe right on iOS, press & hold on Android, right click on Windows).
3. Select Delete
4. Select OK to confirm deletion.

**Expected behavior**
At this point, the account should be deleted, but it is not, and remains visible on screen.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS
 - Version 12.1.4 (16D57)

**Android Studio Emulator:**
 - Device: Nexus 5X API 28 x86
 - OS: Android
 - Version 9.0

**Tablet:**
 - Device: Acer B1-780
 - OS: Android
 - Version 6.0

**Additional context**
n/a

**Comment by NPadrutt** [comment]
this is fixed. Thanks @RobBentleyDev !
