### ISSUE TITLE
App Crashes when started from hibernation

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1544]
**Describe the bug**
When the application is started from scratch everything works. But when it is already started and hibernated the app will crash

**To Reproduce**
1. start application
2. click home button
3. wait for 30 minutes
4. click launcher icon and see crash

**Expected behavior**
The app should start without a crash.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows

**Smartphone (please complete the following information):**
 - Device: All Androids 
 - OS: Android 
 - Version 9, probably 8 and 8.1

**Additional context**

**Comment by NPadrutt** [comment]
I opened a StackOverflow question:
https://stackoverflow.com/questions/55650473/mvvmcross-could-not-find-a-setup-class-for-application

**Comment by Longtrainz** [comment]
Hi Npdarutt, how have you resolved this issue? I have the same trouble with my Xamarin Android app.

**Comment by NPadrutt** [comment]
I replaced MvvmCross with MvvmLight
