### ISSUE TITLE
What should be displayed in live tiles?

### ISSUE THREAD

**Issue by IsaacMorris1980** [MoneyFox/MoneyFox#1564]
**Is your feature request related to a problem? Please describe.**
Currently live tiles displays account balance on a smal tile, medium display balance and look at expenses this month and last month. and finially on the large tile it displays the above information and some of the previous payments(expenses, transfers,and income)

**Describe the solution you'd like**
I would like the information displayed to be of more use to the user.

**Describe alternatives you've considered**
Considered were balance currently and a forecast of the balance at the end of the month.
Showing last month, this month, next month(forecast).   Adding buget information  to show currently where the account fits into the buget if not excluded from a buget.

Looking to see what others would think would be good information to display on live tiles for windows

**Comment by NPadrutt** [comment]
Nice suggestions.
I think for showing the last month we would have something like in #1148.
The forecasting would be pretty interesting too. We could use that for a statistic page as well (for example in #1340) or first implement #356 and use that. 
What easily should be possible is the balance at the end of the current month.

**Comment by IsaacMorris1980** [comment]
@NPadrutt  The balance at the end of the current month would  only be a forecast as we would only have re-occuring payments that we would be able to use for figuring out balance at the end of the month it would have to be update for each new payment that is entered.  I like the budget idea but unsure what to display since a budget could encompass multiple accounts.

**Comment by NPadrutt** [comment]
@IsaacMorris1980  the reoccuring but also all payments already entered. That would basically be the same as you have on top of the account list. The refresh should be handled by the background task automatically.
regarding the budget I think the big question is how we would implement that one. There are some things to consider. But I don't think that it would be an issue that a budget spans multiple accounts, at least for the main tile. For the the individual account we could introduce something like a spending limit after which you get notified and display how far you are into that.

**Comment by NPadrutt** [comment]
Closed since we currently do not seem to be activly working on this. Please feel free to reopen when that changes.
