### ISSUE TITLE
AutoSuggestBox for search

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1604]
**Describe the solution you'd like**
To make search easier it would be nice if there are categories suggested once you start typing. This can be accomplish with the AutoSuggestBox on UWP.

**Comment by heathen89** [comment]
Is this still relevant?
To my knowledge it already works like this.

![image](https://user-images.githubusercontent.com/44643241/74812279-7c0d5300-52f3-11ea-90fc-defd61e1c3a5.png)

**Comment by NPadrutt** [comment]
The idea was to use the AutoSuggestBox  instead of a dedicated dialog on UWP. My thought was, that it could be more straight forward since you don't have to navigate to a separate page. 
But for the moment I circled a bit back to leave it the way it is now and maybe just use a dialog for a nicer appearance.

**Comment by NPadrutt** [comment]
I think for the moment we can close that. If there is a concrete idea of improve the selection in such a way please reopen.
