### ISSUE TITLE
Introduce TeachTips

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1606]
With teaching tips we could show a new user important and maybe not self explanatory menus and options, for example the balance control on top of the account or payment list.
Also we can highlight new features in the future.

**Comment by feokuma** [comment]
Can I try to implement this feature?

**Comment by NPadrutt** [comment]
Sure, be my guest! :)
 Let me know if you need something.

**Comment by feokuma** [comment]
Probably with the text of tips. I'll post some screenshots here.

**Comment by feokuma** [comment]
Hi @NPadrutt. Let me ask you.. We will show a tip only once right? I mean, we need to save this event to avoid show always the same tip. Is this it?

and which menus will show the tip beyond the balance control?

**Comment by NPadrutt** [comment]
Also, how about show a teaching tip on an account when the first was created to highlight that you can find the payments by clicking on the account? No idea how easy or hard that would be to accomplish though :)

**Comment by feokuma** [comment]
Hum. I'm going to start with the settings and tip the payment menu item, then an open a PR. When it works properly we move on another items. What do you think?

**Comment by NPadrutt** [comment]
sounds good :)

**Comment by feokuma** [comment]
Hi @NPadrutt. Sorry about my delay. I had a problem with my windows computer and I am waiting for a new one from Dell. I will return to the issue as soon as possible.

If someone else wants to work before then, I understand 😓

**Comment by NPadrutt** [comment]
@feokuma Sorry to hear that. I hope you're up and running again soon :)
Don't worry about the issue. It will be here for when you're back setup with everything.

**Comment by feokuma** [comment]
I'm back! 🎉

**Comment by NPadrutt** [comment]
@feokuma  welcome back :)

**Comment by NPadrutt** [comment]
Since teaching tips where a UWP / WinUI specific feature this is obselete for the moment
