### ISSUE TITLE
Add "require note" checkmark when creating a category

### ISSUE THREAD

**Issue by Sreini** [MoneyFox/MoneyFox#1607]
When creating a category, it would be useful to be able specify if an entry (expense, income) that falls undee that category should require a note or note. Users (me) have general categories under which they record one-off expenses. Forcing myself to add a note to every such entry can help with reminding me to keep track of what such expenses were actually for.

This should be easy to implement, and I would be willing to do this. But it might also be a cool "up-for-grabs" feature.

**Comment by NPadrutt** [comment]
That sounds like a nice addition. Feel free to go on if want to implement that :)

**Comment by NPadrutt** [comment]
@Sreini  I wanted to check in with you if you want to pick this up yourself or if I should have a look at it?

**Comment by Sreini** [comment]
@NPadrutt feel free to pick it up, I can't really say when I will do it myself so if you want to work on something feel free.

**Comment by feokuma** [comment]
this feature should show a warning window without closing the registration screen of the category?

**Comment by NPadrutt** [comment]
Exactly. You would get a warning or an error when you try to save a payment with a category assosciated whith this flag set.

**Comment by feokuma** [comment]
I tried create a new field on Category Entity but I don't know how can I generate a migration. I tried to run `dotnet ef migrations add...` but I don't understand how to do this.. :(

**Comment by feokuma** [comment]
@NPadrutt what do you think? Simple right? 🙂

![Screenshot 2020-10-05 235447](https://user-images.githubusercontent.com/9166406/95153627-3f994500-0766-11eb-943d-338f7f6f302b.png)

**Comment by NPadrutt** [comment]
That looks nice  👍 
The detail I would change is to make it align left with the textbox. :)

**Comment by feokuma** [comment]
@NPadrutt I thought that issue would be closed automatically when the merge terminated 🤔

**Comment by NPadrutt** [comment]
mh, I think you have to write "fix #[number]". At least that seemed to work when I tried it the last time ^^
