### ISSUE TITLE
Automatic Theme change when device theme is changed

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1639]
On Android and iOS there is currently only the option to change the theme manually to light or dark. 
With Android Q and IOS 13 a dark theme support is introduced, so we should support to change the theme based on the OS setting.

Android doc for dark theme: https://developer.android.com/preview/features/darktheme

**Comment by siddharth952** [comment]
I would like to implement this in the iOS version of the app.

**Comment by NPadrutt** [comment]
Great! :) I'll mark it as in progress for you. Let me know if you need something.

**Comment by siddharth952** [comment]
@NPadrutt I am not able to find the iOS project files in this repo, please help me out.

**Comment by NPadrutt** [comment]
MoneyFox.Ios. see here: https://github.com/MoneyFox/MoneyFox/tree/master/Src/MoneyFox.Ios

**Comment by siddharth952** [comment]
Okay, so the project is using Xamarin.

**Comment by NPadrutt** [comment]
Exactly, yes.

**Comment by NPadrutt** [comment]
hey @siddharth952 
Just wanted to check in with you if you are still working on this or if I should give that back to the pool?

**Comment by siddharth952** [comment]
@NPadrutt Please give this issue back to the pool, I'll work on this later if it happens to be open.

**Comment by CharleeBrown** [comment]
I'll take this over.

**Comment by NPadrutt** [comment]
@CharleeBrown  awesome! :)

**Comment by NPadrutt** [comment]
@CharleeBrown I just stumbled over this article https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/theming/system-theme-changes

In case it helps :)

**Comment by NPadrutt** [comment]
This is solved with v7.0. Although currently it takes a restart of the apl.
