### ISSUE TITLE
Change double datatype to decimal

### ISSUE THREAD

**Issue by Sreini** [MoneyFox/MoneyFox#1645]
**Describe the bug**
In some cases, adding transactions will lead to rounding that is not intended. This is due to the `double` data type used within the code base to represent monetary values.

**To Reproduce**
Add an expense with a value 17.81. You will see that the expense is saved and processed as 17.80.

**Expected behavior**
An expense is added with value 17.81.

**Additional Context**
`double` is not an appropriate data type with which to handle money and financial calculations. The `decimal` data type needs to be used instead. Need to also check if we need to change the data type in the database or not.

**Comment by NPadrutt** [comment]
Thanks for the issue!
I checked the SQLite documentation after our Slack discussion (https://www.sqlite.org/datatype3.html). For floating Point numbers there is just one type: REAL. Therefore that shouldn't lead to any issues on the database if we change that type.

Do you want to resolve this issue yourself?

**Comment by Sreini** [comment]
Yes, I wouldn't mind. Although on the other hand the energy and time I have to contribute varies, and this is a potentially serious issue. I'll see if I can finish this.

**Comment by NPadrutt** [comment]
Alright. I marked it as in progress for you. In case something changes and you don't have the time / energy to finish this just let me know.

**Comment by Sreini** [comment]
This issue should be solved with the last merge. Therefore I'm closing it.
