### ISSUE TITLE
How to create migrations

### ISSUE THREAD

**Issue by feokuma** [MoneyFox/MoneyFox#1874]
I couldn’t find documentation on how to create Migrations in the project. if it really doesn't exists I could create and in the same time implement a improvement

**Comment by NPadrutt** [comment]
Basically it doesn't differ from the default way how to create migrations with EF core https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli

The only thing to note is that you have to set the Migration Helper Project as the startup project and select the persistence project as the target in the PackageManager console.

**Comment by feokuma** [comment]
I found the instructions here: [MoneyFox/MigrationCommand.txt](https://github.com/MoneyFox/MoneyFox/blob/master/MigrationCommand.txt)

Sorry @NPadrutt ... 😅

**Comment by NPadrutt** [comment]
@feokuma uuh, that is a good hint since they are pretty sure out of date given that the DataAccessLayer Project no longer exists ^^
