### ISSUE TITLE
Grid should be sorted when clicked on a column header

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1890]
**Describe the solution you'd like**
Currently the grid on windows can't be sorted. This should be possible when clicked on a user clicks on a column header.

**Comment by pghdeveloper** [comment]
Looking into this.

**Comment by NPadrutt** [comment]
hey @pghdeveloper
how you coming along with this?

**Comment by NPadrutt** [comment]
This is obsolete
