### ISSUE TITLE
Dark theme for message dialog

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1891]
**Is your feature request related to a problem? Please describe.**
Message dialogs are always in the light theme.

**Describe the solution you'd like**
There should be a custom message dialog implementation based on the content dialog.

**Describe alternatives you've considered**
Enable a dark theme for content dialog, although I don't think that this is currently supported.

**Comment by robobunny** [comment]
Would you mind assigning me to this issue? I'm trying to learn C# and I think I could handle this. It may take a while but as the issue was created a couple months ago I hope that's OK. Thanks!

**Comment by NPadrutt** [comment]
@robobunny  done! Let me know if I can help :)

**Comment by NPadrutt** [comment]
hey @robobunny 
I just stumbled over an github issue mentioning that you can just use content dialog instead of message dialog. I created a PR for that  #1954.
I hope you haven't invested too much time in this already. Also would love to look with you at another issue, that might be better suited for learning c# :)
