### ISSUE TITLE
Deemphasize future payments

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1949]
**Is your feature request related to a problem? Please describe.**
Future payments and already cleared one are not very good to keep apart.

**Describe the solution you'd like**
Deemphasize future payments in the list.

**Comment by kg8z** [comment]
@NPadrutt - I can take this one.

**Comment by NPadrutt** [comment]
Great :)

**Comment by kg8z** [comment]
@NPadrutt  - How does this look as a way of deemphasizing future transactions? Adjusting the opacity seems to be a quick and simple way to achieve the effect.
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/81488531/201580258-173d3e26-bde7-46e2-9157-c0bfee699d37.png">

**Comment by NPadrutt** [comment]
Your screenshot looks like I had it in mind. If you have a quick an easy way for that, awesome :)

**Comment by kg8z** [comment]
Awesome. Yep, it's actually quite easy. I need to test on Android and iOS but expect it will look the same.

**Comment by kg8z** [comment]
@NPadrutt - I've been able to get the updated MAUI project to work for Android but iOS is eluding me. It seems (though I'm not 100% certain) that the problem has to do with my development signing certificate having been revoked. Here's the error when I try to configure the iOS Bundle Signing in VS.Net. Thoughts?
<img width="536" alt="image" src="https://user-images.githubusercontent.com/81488531/202611000-647279d3-bb7c-44b4-8572-1bc3e3973422.png">

**Comment by NPadrutt** [comment]
@kg8z Mmh, I might have revoked your certificate by accident. But you should be able to recreate it. Your permissions should be unchanged.

**Comment by kg8z** [comment]
@NPadrutt - Thanks. It turns out I was being dense. Apparently, being out of this for a few months made me rusty. All good now. I'm able to test on iOS.

**Comment by NPadrutt** [comment]
@kg8z Ah nice. :) the whole iOS development is quite complicated. So easy to get confused there.
