### ISSUE TITLE
Warning if end of month balance for account is negative

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1950]
**Is your feature request related to a problem? Please describe.**
It's easy to oversee when an account is in the negative at the end of the month.

**Describe the solution you'd like**
Change the color of the account in lists to hightlight the negative balance.

**Describe alternatives you've considered**
- Send a notification when a payment is created that puts the account in the negatives
- Show a warning sign on list items when they are to be negative.

**Comment by kg8z** [comment]
@NPadrutt - Did you have something like this in mind? We could do this everywhere a balance is displayed that's a negative number.  I can grab this one.
<img width="544" alt="image" src="https://user-images.githubusercontent.com/81488531/164355002-e261cf7b-94e5-4a10-afdf-da7a5b6059ec.png">

**Comment by NPadrutt** [comment]
@kg8z exactly, something along this lines I had in mind :)

**Comment by NPadrutt** [comment]
@kg8z  just a quick warning: I'm still trying to improve the structure of the project and moved some classes around in the MoneyFox.Core project. In case you make adjustments on one of the queries there it might be good if you merge first to avoid a merge conflict.

**Comment by kg8z** [comment]
@NPadrutt - Thanks for the heads-up. I’ll merge the changes ASAP.

**Comment by kg8z** [comment]
@NPadrutt - This can be closed, right?

**Comment by NPadrutt** [comment]
Correct!
