### ISSUE TITLE
Remember number of selected categories shown in spreading

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1968]
**Describe the solution you'd like**
When I change the number of categories shown in the category spreading I want this to be persisted, so that the next time I open it, it shows the same again.

**Comment by shaysw** [comment]
Hi @NPadrutt, I'm new to your repo and OSS in general, was thinking of trying to tackle this. Is the issue still relevant?

**Comment by NPadrutt** [comment]
hey @shaysw 
I still think this would be a nice addition, so go for it if you want to try it! :)

**Comment by NPadrutt** [comment]
With the migration to .net maui this option is no longer available. So this filter would have to be added in general. To avoid confusion I close this issue and created a new one https://github.com/MoneyFox/MoneyFox/issues/2741
