### ISSUE TITLE
Fix Java.IO.IOException: \n not found: size=0 content=... in Crash Group # 3718418361u

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1976]
### Reason ###

Java.IO.IOException: \n not found: size=0 content=...

### Link to App Center ###

* [https://appcenter.ms/orgs/MoneyFox/apps/MoneyFox-Android/crashes/errors/3718418361u](https://appcenter.ms/orgs/MoneyFox/apps/MoneyFox-Android/crashes/errors/3718418361u)

**Comment by kg8z** [comment]
@NPadrutt - Anything I can do to help troubleshoot this? I wasn't able to grab the crash dump from App Center (data expired?).

**Comment by NPadrutt** [comment]
I think we close this issue. The error didn't occur anymore in the last 30 days and it was from an older version. Also this was with Android 7 and it seems that this happened mainly with one device type:
![image](https://user-images.githubusercontent.com/1764367/155937771-65685d2a-3dc8-4781-a7ea-dac4b545f30e.png)
