### ISSUE TITLE
Fix System.IO.FileLoadException: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird. (Exception from HRESULT: 0x80070020) in <LoginSilentAsync>d__21.MoveNext ()

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1979]
### Stacktrace ###

MoneyFox.Application.Common.CloudBackup.OneDriveService.<LoginSilentAsync>d__21.MoveNext() + 0x1cd;MoneyFox.Application.Common.CloudBackup.OneDriveService

MoneyFox.Application.Common.CloudBackup.OneDriveService.<GetBackupDateAsync>d__26.MoveNext() + 0x32b;MoneyFox.Application.Common.CloudBackup.OneDriveService

MoneyFox.Application.Common.CloudBackup.BackupService.<GetBackupDateAsync>d__20.MoveNext() + 0x16e;MoneyFox.Application.Common.CloudBackup.BackupService

MoneyFox.Application.Common.CloudBackup.BackupService.<DownloadBackupAsync>d__22.MoveNext() + 0xf1;MoneyFox.Application.Common.CloudBackup.BackupService

MoneyFox.Application.Common.CloudBackup.BackupService.<RestoreBackupAsync>d__21.MoveNext() + 0x1d5;MoneyFox.Application.Common.CloudBackup.BackupService

MoneyFox.Uwp.Services.StartupTasksService.<StartupAsync>d__2.MoveNext() + 0x5c8;MoneyFox.Uwp.Services.StartupTasksService

MoneyFox.Uwp.Services.ActivationService.<ActivateAsync>d__4.MoveNext() + 0x460;MoneyFox.Uwp.Services.ActivationService

MoneyFox.Uwp.App.<OnLaunched>d__4.MoveNext() + 0x253;MoneyFox.Uwp.App

__Interop.ComCallHelpers.Call(__ComObject, RuntimeTypeHandle, Int32) + 0xb8;__Interop

__Interop.ForwardComStubs.Stub_20[TThis](__ComObject, Int32) + 0x24;__Interop

### Reason ###

System.IO.FileLoadException: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird. (Exception from HRESULT: 0x80070020)

### Link to App Center ###

* [https://appcenter.ms/orgs/MoneyFox/apps/Money-Fox-Windows/crashes/errors/536788250u](https://appcenter.ms/orgs/MoneyFox/apps/Money-Fox-Windows/crashes/errors/536788250u)

**Comment by kg8z** [comment]
@NPadrutt - Anything I can do to help troubleshoot this? Google Translate seems to think the issue has to do with resource contention on the file. If there's any additional detail you can provide I'd be happy to give it a look.

**Comment by NPadrutt** [comment]
I close this aswell. The issue states that the process couldn't access the file since it was used by another file. Problably meaning that the DB file was locked. But that was with UWP and in the current master we moved to WinUI 3 plus other changes in the last versions. And here aswell was the issue only reported by one device.
