### ISSUE TITLE
Transaction displayed wrongly when change payment type from transfer to expense

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#2010]
**Describe the bug**
When you change the payment type from transfer to expense the payment is shown on the target account.

**Comment by kg8z** [comment]
@NPadrutt  - Are you OK with me taking this one? It looks like the Target Account value isn't cleared when the transaction type is changed to Expense (and presumably Income for that matter). I can take a crack at fixing it.

**Comment by NPadrutt** [comment]
sure!

**Comment by kg8z** [comment]
@NPadrutt - I just submitted a PR with the fixes for this bug. Note, I added a new test case that validates the account balances are properly updated when the Payment Type on a transaction is changed from Transfer to either Expense or Income. This is my first PR on GitHub so please let me know if I didn't anything incorrectly.

**Comment by NPadrutt** [comment]
Fixed :) Thanks @kg8z  for your PR
