### ISSUE TITLE
IOS App Bug, can’t type a decimal in the app

### ISSUE THREAD

**Issue by giovannidendekker** [MoneyFox/MoneyFox#2025]
Problem:
When i want to change the amount of a payment or the balance of a new account in the iOS app then I can’t type a decimal number because the app wants a “.” for decimal but the keyboard in iOS only shows a “,” so I always get a full number when i add the amount or add a balance to the new account.

1. Go to dashboard or accounts
2. Click on the “+”
3. Type in the amount field a decimal number

Expected:
I expected a decimal when i type in the “,” but it doesn’t do anything.

Device:
 - Device: IPhone XS Max
 - OS: iOS14.2
 
 App:
 - Version 7.3.7800

**Comment by NPadrutt** [comment]
hey @giovannidendekker 

what language and regional settings do you have? Those are bascially what determine what seperator sign it uses.

**Comment by giovannidendekker** [comment]
Keyboard and IPhone language is English (US) and the region is Netherlands

**Comment by NPadrutt** [comment]
I did some experimenting. The separator sign on the keyboard is shown based on the Region of your phone. Though we take the culture from the language to convert. I'm seeing if we can get the region for the convertions.

**Comment by NPadrutt** [comment]
@giovannidendekker  the change is release in a testflight. In my tests this solves the issue. If you find a moment to have a look at it, to make sure it really is fixed it would be greatly appreciated. Otherwise I hope to release it soon to production.

**Comment by giovannidendekker** [comment]
Hey @NPadrutt 

Thank you for trying to fix it and yes i would like to test it. I downloaded "Testflight" but i need a link or code i think.

**Comment by NPadrutt** [comment]
@giovannidendekker  you can take the Beta Link from the README: https://testflight.apple.com/join/ycYtjupl

**Comment by giovannidendekker** [comment]
I tested it and it works now yes :) But when i make a new account and type in the current balance then it won't work so i think it only works now when u add a payment.

**Comment by NPadrutt** [comment]
@giovannidendekker ah, right. I think I found that issue as well. You should get a fix with the next testflight update.

**Comment by giovannidendekker** [comment]
Awesome, thank you 👍 @NPadrutt

**Comment by NPadrutt** [comment]
@giovannidendekker  the fix for this should be in the store. Could you verify that quickly?

**Comment by giovannidendekker** [comment]
@NPadrutt Yes it works there too now 👍

**Comment by NPadrutt** [comment]
alright. Then I close this issue.
