### ISSUE TITLE
New Filter for Payment Type in Payment List

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#2141]
There should be a easy way to filter for income, expenses and transfers in the payment list.

**Comment by pree-T** [comment]
May I work on this ?Can someone help me as I am new to open source contribution?

**Comment by NPadrutt** [comment]
sure, would love to see your contribution!
I'm also happy to help you if I can. Just let me know if you are struggling somewhere.

**Comment by kg8z** [comment]
@NPadrutt  - Is this what you had in mind for the enhancement? If so, @pree-T  - I'd be happy to work on this with you on this.  I've already done the legwork on updating the Pages and ViewModels. But there's still some work to wire up the functionality and test across devices.

<img width="118" alt="FilterScreenPaymentTypeList" src="https://user-images.githubusercontent.com/81488531/154618846-c8842bb9-4584-44e4-b088-6e58aff91880.png">
<img width="113" alt="FilterScreen" src="https://user-images.githubusercontent.com/81488531/154618847-07892a35-1f1b-4910-bc3b-bc4b40567d8a.png">

**Comment by NPadrutt** [comment]
@kg8z yeah exactly. Something like that was what I have in mind.

**Comment by kg8z** [comment]
@NPadrutt - Want me to take this one or wait for @pree-T to respond?

**Comment by NPadrutt** [comment]
@kg8z  I would wait for like another 2-3 days, just in case. Would hate for @pree-T  being in holidays or something like that and because of that missing this.
But maybe you'll find another issue that sounds interessting to you in the meanwhile :)

**Comment by NPadrutt** [comment]
Given that we haven't heared anything here from @pree-T  I would open that up again.
@kg8z   if you are still interessted let me know.

**Comment by kg8z** [comment]
@NPadrutt - Sure. Send it my way. If @pree-T decides to jump in later we can work together.

**Comment by NPadrutt** [comment]
fixed with #2243
