### ISSUE TITLE
Modification Date and Creation Date columns empty in Payment List

### ISSUE THREAD

**Issue by kg8z** [MoneyFox/MoneyFox#2262]
**Describe the bug**
The columns for Modification Date and Creation Date are both blank in the payment list for accounts.

**To Reproduce**
1. Click on any account that contains at least one payment
2. Note the empty cells for Modification Date and Creation Date in the list

**Expected behavior**
The Modification Date and Creation Date cells should contain the last date on which each payment was modified and the date each payment was created, respectively.

**Screenshots**
<img width="947" alt="image" src="https://user-images.githubusercontent.com/81488531/161455639-38d0d62c-f89e-4891-9f1d-5bdc6a6da593.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Comment by kg8z** [comment]
@NPadrutt  - I already have a fix for this in the codebase I'm working on for issue #2039. Feel free to assign this one to me. I can either include the fix with the PR for that issue (which will likely take some time because of the complexity of the enhancement), or I can submit a separate PR to fix this issue ASAP. Let me know which you prefer.

**Comment by NPadrutt** [comment]
thanks for reporting and fixing @kg8z  
if submitting a pr for this issue separately only takes little time I would say go for it. Then we can potentially fix this soon already. if it would take a lot of time then
