### ISSUE TITLE
Maintain integrity of recurring payment schedule if the application isn't run regularly

### ISSUE THREAD

**Issue by kg8z** [MoneyFox/MoneyFox#2285]
**Is your feature request related to a problem? Please describe.**
The current logic to trigger payment creation for recurring payments will miss transactions if the application hasn't been run within 2 cycles of the recurrence period (e.g. weekly, last run >14 days ago). Consider the following scenario...

There is a recurring payment created for a weekly Friday paycheck where the last recurrence creation date was March 18, 2022. Today is April 3, 2022 and the person runs the MoneyFox application for the first time since returning from holiday. Two Fridays have passed while the person was on holiday (March 25 and April 1). The current behavior of the application creates a single payment transaction for today's date, April 3, 2022, which not only breaks the weekly cadence but also changes the day of week of the series.

_Note: You can simulate this by creating a new Payment with a date more than two weeks in the past, Recurring=Yes, Recurrence=Weekly. Close and rerun the app to trigger the recurring transaction creation._

**Describe the solution you'd like**

It seems to me that the recurrence date calculation should be based on the start date of the recurring payment object and all instances of recurrence should be generated if the user hasn't run the application in a while. In the aforementioned scenario, I would expect the 2 payment transactions to be created automatically, keeping to the same day of the week. This would have happened if I ran the app regularly, but not if there was a gap. Basically, I would expect the same transactions to be created whether I run the app daily or leave it for a period of time (which is not the case currently).

**Describe alternatives you've considered**
Utilize a background process or some other mechanism that triggers recurring payment transactions daily even if the application isn't run. This approach isn't effective if the computer is powered down.

**Additional context**

**Comment by NPadrutt** [comment]
With the new implementation of the recurring payment this should be fixed.
Thanks for reporting :)
