### ISSUE TITLE
Merge Mobile and Windows UI code

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#2290]
**Describe the solution you'd like**
Currently there is a UI project for Windows and one for Mobile since Xamarin Forms never really supported desktop. Since .net MAUI comes with full support for Desktop we should evaluate to merge and therefore simplify the code base.

**Describe alternatives you've considered**
In case the effort to have a nice Desktop UI would be very high or the result just not very good there is the option to keep the separate ui projects.

**Comment by kg8z** [comment]
@NPadrutt  - I'd love to collaborate with you on this once MAUI is released.

**Comment by NPadrutt** [comment]
@kg8z  would love to! I'm currently trying to migrate the current mobile solution to MAUI. After that we can see what kind of optimization for desktop are needed to replace the dedicated windows version.
That being said, I'm on holidays in the US for the next two weeks. So I might not have not too much time till I'm back.

**Comment by NPadrutt** [comment]
hey @kg8z 
I opened a PR that moves windows to MAUI in a first step to merge the mobile and desktop version. In case you want to join in on a better desktop experience (with maybe improve the mobile one as well) feel free to commit changes to the PR! :)

**Comment by kg8z** [comment]
@NPadrutt  - Thanks for letting me know! I'm still easing back into my evening dev work so it may take me time to ramp up. But I definitely want to help with the MAUI transition.

**Comment by NPadrutt** [comment]
this is solved in a first round.
Optimizations for windows can be added going forward
