### ISSUE TITLE
Expense/Income Values Not Formatted Properly

### ISSUE THREAD

**Issue by kg8z** [MoneyFox/MoneyFox#2597]
**Describe the bug**
The Expense & Income values in the group header of the PaymentListPage view are not formatted. They should be in currency format but instead are raw numbers.

**To Reproduce**
1. Open any account
2. Look at the group head for any of the transactions
3. The numbers will not have currency formats

**Expected behavior**
Add currency formatting to the Income & Expense values in the group header.

**Screenshots**
<img width="934" alt="GroupHeaderMissingFormatting" src="https://user-images.githubusercontent.com/81488531/201566008-bb8b7f33-5be9-4b20-b5b3-3498f4017f94.png">

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Version	10.0.22621 Build 22621

**Additional context**

**Comment by kg8z** [comment]
@NPadrutt - Please assign this to me. I have a fix ready for a PR. Thanks.

**Comment by NPadrutt** [comment]
@kg8z  done
