### ISSUE TITLE
Inconsistency in the naming: "MoneyFox" vs. "Money Fox"

### ISSUE THREAD

**Issue by kres0345** [MoneyFox/MoneyFox#2608]
**Describe the bug**
The strings following strings spell "MoneyFox": CompletedText, WelcomePageText
The following strings spell "Money Fox" or "the Money Fox": FeedbackSubject, TranslationLabel, The name of the app.

Also, is it "the Money Fox" or just "Money Fox", personally I just use "Money fox" as it would otherwise sound silly when translated into my language.

**Expected behavior**
Be consistent.

**Comment by NPadrutt** [comment]
Thanks for bringing that up. I agree that it should be without any "the". I would go for "MoneyFox". I'll adjust the strings and translations.

**Comment by NPadrutt** [comment]
@kres0345  with the PR #2617  this should be cleanup as much as possible.
