### ISSUE TITLE
Graph Error message when logging into OneDrive

### ISSUE THREAD

**Issue by krestenlaust** [MoneyFox/MoneyFox#2609]
**Describe the bug**
When synchronizing with OneDrive, it shows an error message, but I've no issues otherwise.

**To Reproduce**
Connect to OneDrive. When finished logging in with the SSO login screen, it returns to the app with the error message: "`Call failed with status code 403 (Forbidden): GET https://graph.microsoft.com/v1.0/me`"

I've always gotten this message. Simply pressing 'OK' dismisses it and shows that the connection was still made. I've had no problems with actual synchronization.

**Expected behavior**
Not show an error message when no error occurred (as far as the user is concerned)

**Screenshots**
![316430488_535349538460077_998278593353206708_n](https://user-images.githubusercontent.com/17174333/203650648-e7aa256c-1025-48d6-9a0b-0a8457793f64.jpg)
Caption: "**Could not login** A problem occured. Error message Call failed with status code 403 (Forbidden): GET https://graph.microsoft.com/v1.0/me"

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T and Samsung A5 (2017) (My previous phone)
 - OS: Oxygen 11.1.2.2 (Android 11) and Android 8, respectively.
 - Version: Every version I've tried. Also latest manual build.

**Comment by kres0345** [comment]
Also the circle I suspect to contain a profile picture is just white, even though I do have a profile picture.
![316018121_8188973857840091_8543839253449446457_n](https://user-images.githubusercontent.com/17174333/203652714-3a218973-a2da-4eb5-9be5-cf7a2c4907c7.jpg)

**Comment by NPadrutt** [comment]
@kres0345  can you check what the error was here? you should find that in the log which you can open via the about page.

**Comment by NPadrutt** [comment]
awesome! thanks for the update @krestenlaust and the feedback to the new look :)

**Comment by krestenlaust** [comment]
Of course, have been a bit distracted lately, might try to look into making a PR sometime. Is the migration to the new framework finished?

**Comment by NPadrutt** [comment]
yes! we are on the latest version of .net and maui!

**Comment by krestenlaust** [comment]
Awesome!
