### ISSUE TITLE
Can't open transactions from account view

### ISSUE THREAD

**Issue by kres0345** [MoneyFox/MoneyFox#2657]
**Is your feature request related to a problem? Please describe.**
I was very confused when I tried to open transaction overview when viewing my accounts. I tried pressing on an account but it didn't work. Then I went back to the frontpage and pressed on an account and from there it worked.

**Describe the solution you'd like**
An intuitive user experience. Tapping on an account should show the transactions associated, as it does from the frontpage.

**Additional context**

Device: Android, OnePlus 6T
Version: Android 11
App version: 1.0

**Comment by NPadrutt** [comment]
Thanks for reporting. There seems to be a problem in the Android Version. On iOS it works, albeit very slowly.
What version are you currently using? Something in the area of  7.9 or 7.8 would make sense.

**Comment by kres0345** [comment]
where can I read the version? The app just says version 1.0

**Comment by NPadrutt** [comment]
If you run an officially released version from one of the stores the version should be displayed in the about page. Given you have a 1.0 I presume you run it via visual studio yourself?

**Comment by kres0345** [comment]
Oh, right. An installation from the Play Store still results in a crash for me, (#2595) installing from Visual Studio solved this. Just confirmed this by reinstalling from the Play Store, same error.
