### ISSUE TITLE
Category updates always fail

### ISSUE THREAD

**Issue by kg8z** [MoneyFox/MoneyFox#2684]
**Describe the bug**
When an existing category is edited, clicking the _Save_ button always results in the error "A category with that name already exists." unless the name is changed as part of the edit operation. This is happening because the check for duplicate category names does not exclude the currently opened category from the check. As a result, the ViewModel detects that a category already exists with the same name.

**To Reproduce**
1. Click on the _Categories_ menu option
2. Click on any existing category in the list to open it
3. Make a change to any field other than Category Name
4. Click the _Save_ button
5. See error

**Expected behavior**
The category being edited should be excluded from the check for duplicate names. The save option should complete without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/81488531/213355928-d622a821-da34-4cc4-8fc5-c855a85b6b7d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kg8z** [comment]
@NPadrutt  - You can assign this one to me. I'll get a fix queued up.

**Comment by NPadrutt** [comment]
very cool thank you

**Comment by NPadrutt** [comment]
This should be fixed. Thanks @kg8z
