### ISSUE TITLE
Text overlapping with long category names

### ISSUE THREAD

**Issue by kres0345** [MoneyFox/MoneyFox#2703]
**Describe the bug**
The category text overlaps the 'balance' of a category, when the category name is sufficiently long.

**Expected behavior**
I think that I would expect it to truncate the text and put an ellipsis in the end. Hovering the text would then display the full text in a tooltip. Either that, or something that provides same functionally without a visual glitch.

**Screenshots**
![billede](https://user-images.githubusercontent.com/17174333/215274085-f4607b9d-bcf4-4f63-a50c-7fbd458f0c6c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version [e.g. 22]? (Not sure where to look.)

**Comment by NPadrutt** [comment]
This should be fixed with PR #2706
