### ISSUE TITLE
win moneyfox app ist not starting anymore

### ISSUE THREAD

**Issue by hardyks** [MoneyFox/MoneyFox#2715]
after the latest win updates KB5022360, KB4023057, KB2267602 will not start anymore.
I deleted all datas from the app and reinstalled the win app
no chance

**Comment by NPadrutt** [comment]
hey @hardyks
Thanks for reporting. There is an update on its way which seems to fix that problem as well. It should be available in the next couple of hours. Could you check again once it is out and update the isse?

**Comment by hardyks** [comment]
okay, many thanks, win app is starting now.
Bu backup: 
new backup.db is not working
restore backup.db is not working (when trying to restore backup - a little popup says: backup failed

**Comment by NPadrutt** [comment]
Thanks for the feedback. Then I close this issue. The problem since we already have #2671  for the backup issue.
