### ISSUE TITLE
Add filter to choose the amount of categories loaded in category spreading chart

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#2741]
**Is your feature request related to a problem? Please describe.**
Currently the number of categories included in the category spreading is fix. It would be nice if this could be dynamically selected.
This should be persisted to the settings.

**Comment by brazdilj** [comment]
Hello, is this still open? Can I look into this? Thank you for your answer

**Comment by NPadrutt** [comment]
this is still open, yes. I'm happy to assign you to it :)

**Comment by brazdilj** [comment]
Hello, I just created a pull request with my solution (https://github.com/MoneyFox/MoneyFox/pull/3219)
