### ISSUE TITLE
Searchfunction for Transaction based on Comments or Categorie

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#280]

**Comment by sethbartlett** [comment]
Any details on this? I'm going to start knocking out some of the backlog from the oldest first.

**Comment by NPadrutt** [comment]
The basic idea was to provide some kind of search option who looks for payments with these infos. But not sure if it is more handy to just add two filters. One for payment type and one for the category.
But still, then you cant look for a comment.

**Comment by NPadrutt** [comment]
I close issues that are active since a long time in the assumption that it isn't such a big need then. Can be reopened or recreated In case new information come up.
