### ISSUE TITLE
Busy indicator while loading transactions

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#282]

**Comment by MichaelAi** [comment]
This should be easy enough. Do you want an indeterminate progress bar on the top that allows user interactions or something else?

**Comment by NPadrutt** [comment]
I guess I would use the same busy indicator as when you upload a backup.
But it might be that we have to refactor the data loading aswell. Since it's not async it might block the ui thread.

**Comment by MichaelAi** [comment]
I see, that might complicate things.

**Comment by NPadrutt** [comment]
yeah.. but it might be a good idea anyway to make this async. or at least provide both, a sync and a async path to start with.

**Comment by sethbartlett** [comment]
Michael have you made any headway on this or is this still open and available to work on?

**Comment by MichaelAi** [comment]
@sethbartlett this is still open.
