### ISSUE TITLE
Default text in Taskbar

### ISSUE THREAD

**Issue by efinder2** [MoneyFox/MoneyFox#2868]
**Is your feature request related to a problem? Please describe.**
Currently the text in the windows task bar is "WinUi Dektop" and the icon has a blue background. For me it is "hard" to identify it during usage. Using the dark theme the logo is only blue for the most part:
![image](https://user-images.githubusercontent.com/12611194/230774722-ed13a432-3a18-4bd3-9172-c574f34cc9c5.png)

**Describe the solution you'd like**
Set text to MoneyFox and the icon to the Logo with transparent background. 

**Additional context**
Windows 10, Default dark theme 4k resolution.

**Comment by NPadrutt** [comment]
Hey @efinder2 
What Version do you have installed? The Logo actually changed in one of the latest Updates and should look now like this (at least on Windows 11, should be similar on Windows 10):
![image](https://user-images.githubusercontent.com/1764367/230995353-269f4a54-ad16-40b2-9665-dba1aba7134f.png)

**Comment by NPadrutt** [comment]
Since I haven't heared back here in a while I'm going to close this issue. @efinder2 in case this is still a problem feel free to reopen :)
