### ISSUE TITLE
Show current balance in payment list

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#2876]
**Is your feature request related to a problem? Please describe.**
When you select an account to get to the payment list, there is no way to quickly see the current balance of that account.

**Describe the solution you'd like**
The current balance should be displayed in the titlebar or on the left side of the add payment button where there is empty space.

**Comment by balaji119** [comment]
@NPadrutt I see this enhancement is already done.

![image](https://github.com/MoneyFox/MoneyFox/assets/9712538/65388d0b-f784-4b9c-a90a-16f9a91a4e8d)

**Comment by NPadrutt** [comment]
You're right. thank you for pointing that out.
