### ISSUE TITLE
Add option in monthly cash flow for all accounts

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#2954]
**Is your feature request related to a problem? Please describe.**
Monthly cashflow only allows to show the cashflow for one specific account but not all.

**Describe the solution you'd like**
There should be an option to show the cashflow for all accounts.

**Comment by balaji119** [comment]
@NPadrutt I think we can show a maximum of 10 accounts. What should be the approach if there are more than 10 accounts?

**Comment by NPadrutt** [comment]
Hey @balaji119 
My thought was to just sum the value of all accounts per time unit and show them as one bar. Is understandable what I mean?

**Comment by balaji119** [comment]
I got it. Thanks for the explanation @NPadrutt

**Comment by NPadrutt** [comment]
Let me know if you want to takle this. Then I can mark it as in progress for you.

**Comment by balaji119** [comment]
@NPadrutt Yes, I'll pick this up.
