### ISSUE TITLE
Make it mandatory that you have at least one account after setup wizard

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#3021]
**Is your feature request related to a problem? Please describe.**
Currently you can leave the setup wizard and not have an account which is prevents you form basically doing anything.

**Describe the solution you'd like**
The setup should be designed in a way that you have at least one account.

**Comment by Inferlex** [comment]
Hello, is this issue still up? If so, is it possible for me to try and take this?

**Comment by NPadrutt** [comment]
sure, happy if have a go at it. :)

**Comment by NPadrutt** [comment]
hey @Inferlex 
I wanted to quickly check in if you are still working on this? Otherwise I would open this up again.

**Comment by Inferlex** [comment]
Hello. Im sorry for the lack of updates, Im still working on it. I had some problems, but it should almost done.

**Comment by NPadrutt** [comment]
sounds great! looking forward to it :)
