### ISSUE TITLE
Budgetmanagement

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#356]
There shall be a new menu for budget. This Leads to a new page with an overview of the budgets of a user. When a user adds a new one, he can add one or more categories, the budget amount and optional if he want to exclude any accounts.

For each budget there shall be an entry in the list with a "loading bar" who shows with different colors:
1. how much was spent on this budget
2. how much was spent including payments who was creates but not cleared
3. the total budget amount

**Comment by IsaacMorris1980** [comment]
@NPadrutt   Should savings be a sub/extend class from budget. or separate like payment and re-occuring payment?

**Comment by NPadrutt** [comment]
Not sure that I understand that question correct. I think you would have a budget entity class to save the settings you made, but I would probably calculate the savings on the fly. But that would really depend on how you would implement it in the end.

**Comment by IsaacMorris1980** [comment]
@NPadrutt   i would like to attempt this

I plan on doing this in stages

Stage 1 implement spending limits on both accounts and categories

Stage 2 Implement Budgets (non-saving projects)

Stage 3 Implement Budgets (Saving Project and potentially add live tile support )

**Comment by NPadrutt** [comment]
I marked this issue as in progress. so far I'm not sure what the exact difference is between the budget with and the one without saving projects. But I'm sure we'll here more about these once you get there :)

**Comment by IsaacMorris1980** [comment]
When i look back over it you are correct.  I initially thought we would be able to do  statistics over the burn rate to target on a savings project your comment got me thinking we would be able to do the same with the budget will edit above

do you have any ideas when would be a good percentages to send notifications ?
For savings projects  i was thinking 50,75,90,100?
For budgets was thinking 50,75,90,100 and one on each transaction after 100% until end date is reached

**Comment by IsaacMorris1980** [comment]
@NPadrutt   

For stage one  i am considering 2 different options and would like to get feedback on both options:

Option 1 - Add an event and or method to the account and category to be triggered when anything on the account/category changes


Option 2 - Create a background service one each platform that can run on a timer  or subscribe to changes in account/category changes

Not sure which way is better to go. or if you have any better ideas

**Comment by NPadrutt** [comment]
The question is probably what the best experience is for the user. I would probably tend to trigger it when a change is made, so it is transparent for the user what change did cause it to trigger. The difficulty here might be what is with the current background jobs? They probably could cause the change. Also how can you prevent spamming notifications, for example when you clear payments or create recurring payments (depending if you only consider changes of a cleared payment or all created payments)?
In such a case a background task could be more useful since it bundles such notifications. The problem here could be that the task is executed too late to be useful for a user.
Also it is worth to consider that background task especially on iOS are quite restrictive and rather hard to time.
