### ISSUE TITLE
Cortana integration

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#383]

**Comment by NPadrutt** [comment]
I think this is currently only possible on Windows.
My thoughts where for example to create a payment (income, expense, transfer) for you. But of course there is a pretty big room for other ideas :)

**Comment by IsaacMorris1980** [comment]
@NPadrutt  do we want cortana support inside and outside of the app(eg. have people able to create a payment without having the application open initially?)

**Comment by NPadrutt** [comment]
I thought mainly outside. My initial idea was to enable users to create payments really fast and in a very easy manner.

**Comment by IsaacMorris1980** [comment]
I would like to try this

**Comment by NPadrutt** [comment]
Great. I mark it as in Progress for you :)

**Comment by NPadrutt** [comment]
I close that for now. If we hav e a concrete vision for supporting cortana or any other voice assistant feel free to reopen.
