### ISSUE TITLE
Show modify title on transaction modifications

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#432]
Currently in the ModifyTransactionView is always the title "Add Transaction". This should change if you are editing a transaction.
For that we can add a property to the ModifyTransactionViewModel and return a title based on the mode it is.

**Comment by MichaelAi** [comment]
You could just edit to say "save" which is a catch all for "add" and "edit" ;)

**Comment by NPadrutt** [comment]
true ^^
But I think it would be a good thing to have two different titles anyway. Makes it more clear in which mode you are. At least I already had it that I didn't knew anymore if I'm adding or editing :-D

**Comment by MatthewJamesHill** [comment]
Have created a PR #1039 for this. Was making the changes myself but turned out the exact same thing existed already, but was only being used in the android version.

**Comment by MatthewJamesHill** [comment]
I was making the changes for this and came across an auto-property which already implements this feature, although it is only used by the android version so far. Updated the XAML in the ModifyPaymentView and this fixed it...partially.

The title displays correctly but only when there is a new call to the title property, this doesn't always happen depending on how you navigate through the app
