### ISSUE TITLE
Open Context menu where the mouse pointer is

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#699]

**Comment by timothyallsworth** [comment]
how do i contribute to this issue, never done this before, just finished web diploma, my email is timothy.allsworth@yahoo.com.au and i have a portfolio: http://portfoliotim.azurewebsites.net/

**Comment by NPadrutt** [comment]
hi @timothyallsworth 
I guess the easiest way is to make a fork, fix it on this and then make a pull request.  Do you know these mechanisms? 
also I send you an invite for our slack group. that's a bit more efficient when you have questions.
