### ISSUE TITLE
Automatic backup called twice when saving a change

### ISSUE THREAD

**Issue by MichaelAi** [MoneyFox/MoneyFox#940]
UploadBackupIfNewwer() in AutoBackupManager is called twice when adding/editing/deleting a transaction; this is because the method is called once when saving the transaction itself and again when saving the relevant account. As a result there are two instantly subsequent onedrive requests thus the SDK throws an exception.

**Comment by NPadrutt** [comment]
Makes sense.
is that fixed with the change you are doing?

**Comment by NPadrutt** [comment]
guess this should be fixed with your latest PR, right?

**Comment by MichaelAi** [comment]
yes, it's fixed.

**Comment by NPadrutt** [comment]
great, thanks :)
