### ISSUE TITLE
Duplicate categories

### ISSUE THREAD

**Issue by sethbartlett** [MoneyFox/MoneyFox#946]
A category should not be able to be duplicated by name (For example, creating the category "Groceries" 2+ times is possible right now and would make no sense.

**Comment by NPadrutt** [comment]
yeah, that makes sense to prevent. could lead to strange data.

**Comment by NPadrutt** [comment]
Isn't there a way to validate the content of a text box in uwp?

**Comment by sethbartlett** [comment]
Yeah there should be a way to do some validation before they submit, but I'm not sure anything is wired up currently to do that. So a toast notification would work for now.

**Comment by NPadrutt** [comment]
I use a dialog for now. we can tweak this when we see that it is not practical. My biggest concern for now is that categories are created through a dialog. therefore you have a dialog who opens a dialog. I guess this just closes the first dialog and you have to start again.
But I guess it would be a good idea to replace the dialog anyway (see #948).
