### ISSUE TITLE
Changing target account when editing transfer causes balances to not be updated

### ISSUE THREAD

**Issue by kerbowa** [MoneyFox/MoneyFox#971]
It also caused a negative balance in a test account to add to the total amount instead of subtract.

**Comment by wobrek** [comment]
#972

**Comment by NPadrutt** [comment]
This is related to #972

**Comment by kg8z** [comment]
@NPadrutt - Is this still an issue? I tried several permutations of updating transfers and was unable to reproduce.

**Comment by NPadrutt** [comment]
It might well be that your fix for the transfers did fix this too. So I'm closing this for now. Otherwise we can reopen.
