### ISSUE TITLE
Refactor payments to transactions

### ISSUE THREAD

**Issue by sethbartlett** [MoneyFox/MoneyFox#974]
Payments should be changed to "Transactions" in class names and in the UI. It makes more sense for it to be named in this fashion. 

For example, an "income" would still be a transaction but not really a "payment".

**Comment by NPadrutt** [comment]
In fact the name was transaction once.
What is the difference between transaction and payment? Is transaction the more formal version of a payment?

Little detail: there is a system class named transaction. So you will probably have to call it something like FinancialTransaction.

**Comment by sethbartlett** [comment]
A transaction doesn't necessarily have to be a payment and really isn't. If you think of it from an accounting perspective you have an expenses and incomes. 

So really we could potentially have a base class for both of these and actually have two separate lists maybe instead of just an enum. Would allow for easier math as well. Right now the repos have to check a bunch of stuff on whose account is being charged etc. With two lists you could just do balance = incomes -expenses

**Comment by NPadrutt** [comment]
Can't a payment be a expense and a income aswell?

that's an interessting idea indeed..

**Comment by NPadrutt** [comment]
aah, alright that makes sense. Thanks =)

**Comment by NPadrutt** [comment]
Since "transaction" is used in other libraries alread I stay with payments in the code. But we could adjust the translations to reflect the difference.
