### ISSUE TITLE
Move AppBar on MainView and PaymentListView into a own view with his own ViewModel

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#985]

**Comment by wobrek** [comment]
Because the app bars are slightly different should it be two view models or just have the extra functionality in one. Don't know if we should expect these bars to change much.

**Comment by NPadrutt** [comment]
If there is different behavior we can make a base VM and inherit from that for a slightly different behavior. But it is a good point if it should change that much.
