### ISSUE TITLE
Selected Category won't be set on payment

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#989]
This bug seems only to occur on windows, but not on android.

**Comment by wobrek** [comment]
It seems that the category selected message is updating a separate ModifyPaymentViewModel that is not the one associated with the view. If you step through it in the debugger you can see that it actually does save the category you select in some other viewmodel object in memory.

**Comment by NPadrutt** [comment]
Thats interessting.
Funny is, that it still works on android.

**Comment by wobrek** [comment]
The problem is that in windows after Close() is called on the SelectCategoryVM a new ModifyPaymentVM is created. The old view model still exists because it is registered in the message hub. In android when Close() is called this doesn't happen. The old VM is updated and displayed.

**Comment by NPadrutt** [comment]
but in the ModifyPaymentView is NavigationCacheMode="Enabled". IMHO should that conserver the view as well.

**Comment by NPadrutt** [comment]
got it. the cache is reseted when you navigate away. there should be a filter that this only happens when the navigation mode is back. but somehow this was deleted.
